# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/capybara/all/capybara.rbi
#
# capybara-2.18.0
module Capybara
  def self.HTML(html); end
  def self.add_selector(name, &block); end
  def self.always_include_port(*args, &block); end
  def self.always_include_port=(*args, &block); end
  def self.app(*args, &block); end
  def self.app=(*args, &block); end
  def self.app_host(*args, &block); end
  def self.app_host=(*args, &block); end
  def self.asset_host(*args, &block); end
  def self.asset_host=(*args, &block); end
  def self.automatic_label_click(*args, &block); end
  def self.automatic_label_click=(*args, &block); end
  def self.automatic_reload(*args, &block); end
  def self.automatic_reload=(*args, &block); end
  def self.config; end
  def self.configure; end
  def self.current_driver; end
  def self.current_driver=(name); end
  def self.current_session; end
  def self.default_driver(*args, &block); end
  def self.default_driver=(*args, &block); end
  def self.default_host(*args, &block); end
  def self.default_host=(*args, &block); end
  def self.default_max_wait_time(*args, &block); end
  def self.default_max_wait_time=(*args, &block); end
  def self.default_selector(*args, &block); end
  def self.default_selector=(*args, &block); end
  def self.default_wait_time(*args, &block); end
  def self.default_wait_time=(*args, &block); end
  def self.drivers; end
  def self.enable_aria_label(*args, &block); end
  def self.enable_aria_label=(*args, &block); end
  def self.exact(*args, &block); end
  def self.exact=(*args, &block); end
  def self.exact_options(*args, &block); end
  def self.exact_options=(*args, &block); end
  def self.exact_text(*args, &block); end
  def self.exact_text=(*args, &block); end
  def self.ignore_hidden_elements(*args, &block); end
  def self.ignore_hidden_elements=(*args, &block); end
  def self.included(base); end
  def self.javascript_driver(*args, &block); end
  def self.javascript_driver=(*args, &block); end
  def self.match(*args, &block); end
  def self.match=(*args, &block); end
  def self.mode; end
  def self.modify_selector(name, &block); end
  def self.raise_server_errors(*args, &block); end
  def self.raise_server_errors=(*args, &block); end
  def self.register_driver(name, &block); end
  def self.register_server(name, &block); end
  def self.reset!; end
  def self.reset_sessions!; end
  def self.reuse_server(*args, &block); end
  def self.reuse_server=(*args, &block); end
  def self.run_default_server(app, port); end
  def self.run_server(*args, &block); end
  def self.run_server=(*args, &block); end
  def self.save_and_open_page_path(*args, &block); end
  def self.save_and_open_page_path=(*args, &block); end
  def self.save_path(*args, &block); end
  def self.save_path=(*args, &block); end
  def self.server(*args, &block); end
  def self.server=(*args, &block); end
  def self.server_errors(*args, &block); end
  def self.server_errors=(*args, &block); end
  def self.server_host(*args, &block); end
  def self.server_host=(*args, &block); end
  def self.server_port(*args, &block); end
  def self.server_port=(*args, &block); end
  def self.servers; end
  def self.session_name; end
  def self.session_name=(name); end
  def self.session_options; end
  def self.session_pool; end
  def self.string(html); end
  def self.threadsafe(*args, &block); end
  def self.threadsafe=(*args, &block); end
  def self.use_default_driver; end
  def self.using_driver(driver); end
  def self.using_session(name); end
  def self.using_wait_time(seconds); end
  def self.visible_text_only(*args, &block); end
  def self.visible_text_only=(*args, &block); end
  def self.wait_on_first_by_default(*args, &block); end
  def self.wait_on_first_by_default=(*args, &block); end
  extend Capybara::DSL
end
class Capybara::SessionConfig
  def always_include_port; end
  def always_include_port=(arg0); end
  def app_host; end
  def app_host=(url); end
  def asset_host; end
  def asset_host=(arg0); end
  def automatic_label_click; end
  def automatic_label_click=(arg0); end
  def automatic_reload; end
  def automatic_reload=(arg0); end
  def default_host; end
  def default_host=(url); end
  def default_max_wait_time; end
  def default_max_wait_time=(arg0); end
  def default_selector; end
  def default_selector=(arg0); end
  def enable_aria_label; end
  def enable_aria_label=(arg0); end
  def exact; end
  def exact=(arg0); end
  def exact_options; end
  def exact_options=(opt); end
  def exact_text; end
  def exact_text=(arg0); end
  def ignore_hidden_elements; end
  def ignore_hidden_elements=(arg0); end
  def initialize_copy(other); end
  def match; end
  def match=(arg0); end
  def raise_server_errors; end
  def raise_server_errors=(arg0); end
  def run_server; end
  def run_server=(arg0); end
  def save_and_open_page_path; end
  def save_and_open_page_path=(path); end
  def save_path; end
  def save_path=(arg0); end
  def server_errors; end
  def server_errors=(errors); end
  def server_host; end
  def server_host=(arg0); end
  def server_port; end
  def server_port=(arg0); end
  def visible_text_only; end
  def visible_text_only=(arg0); end
  def wait_on_first_by_default; end
  def wait_on_first_by_default=(arg0); end
end
class Capybara::ReadOnlySessionConfig < SimpleDelegator
  def always_include_port=(val); end
  def app_host=(val); end
  def asset_host=(val); end
  def automatic_label_click=(val); end
  def automatic_reload=(val); end
  def default_host=(val); end
  def default_max_wait_time=(val); end
  def default_selector=(val); end
  def enable_aria_label=(val); end
  def exact=(val); end
  def exact_options=(val); end
  def exact_text=(val); end
  def ignore_hidden_elements=(val); end
  def match=(val); end
  def raise_server_errors=(val); end
  def run_server=(val); end
  def save_and_open_page_path=(val); end
  def save_path=(val); end
  def server_errors=(val); end
  def server_host=(val); end
  def server_port=(val); end
  def visible_text_only=(val); end
  def wait_on_first_by_default=(val); end
end
class Capybara::Config
  def always_include_port(*args, &block); end
  def always_include_port=(*args, &block); end
  def app; end
  def app=(arg0); end
  def app_host(*args, &block); end
  def app_host=(*args, &block); end
  def asset_host(*args, &block); end
  def asset_host=(*args, &block); end
  def automatic_label_click(*args, &block); end
  def automatic_label_click=(*args, &block); end
  def automatic_reload(*args, &block); end
  def automatic_reload=(*args, &block); end
  def default_driver; end
  def default_driver=(arg0); end
  def default_host(*args, &block); end
  def default_host=(*args, &block); end
  def default_max_wait_time(*args, &block); end
  def default_max_wait_time=(*args, &block); end
  def default_selector(*args, &block); end
  def default_selector=(*args, &block); end
  def default_wait_time; end
  def default_wait_time=(t); end
  def deprecate(method, alternate_method, once = nil); end
  def enable_aria_label(*args, &block); end
  def enable_aria_label=(*args, &block); end
  def exact(*args, &block); end
  def exact=(*args, &block); end
  def exact_options(*args, &block); end
  def exact_options=(*args, &block); end
  def exact_text(*args, &block); end
  def exact_text=(*args, &block); end
  def ignore_hidden_elements(*args, &block); end
  def ignore_hidden_elements=(*args, &block); end
  def initialize; end
  def javascript_driver; end
  def javascript_driver=(arg0); end
  def match(*args, &block); end
  def match=(*args, &block); end
  def raise_server_errors(*args, &block); end
  def raise_server_errors=(*args, &block); end
  def reuse_server; end
  def reuse_server=(bool); end
  def run_server(*args, &block); end
  def run_server=(*args, &block); end
  def save_and_open_page_path(*args, &block); end
  def save_and_open_page_path=(*args, &block); end
  def save_path(*args, &block); end
  def save_path=(*args, &block); end
  def server(&block); end
  def server=(name); end
  def server_errors(*args, &block); end
  def server_errors=(*args, &block); end
  def server_host(*args, &block); end
  def server_host=(*args, &block); end
  def server_port(*args, &block); end
  def server_port=(*args, &block); end
  def session_options; end
  def threadsafe; end
  def threadsafe=(bool); end
  def visible_text_only(*args, &block); end
  def visible_text_only=(*args, &block); end
  def wait_on_first_by_default(*args, &block); end
  def wait_on_first_by_default=(*args, &block); end
  extend Forwardable
end
class Capybara::ConfigureDeprecator
  def initialize(config); end
  def method_missing(m, *args, &block); end
  def respond_to_missing?(m, include_private = nil); end
end
module Capybara::Helpers
  def declension(singular, plural, count); end
  def inject_asset_host(html, asset_host = nil); end
  def monotonic_time; end
  def normalize_whitespace(text); end
  def to_regexp(text, regexp_options = nil, exact = nil); end
  extend Capybara::Helpers
end
module Capybara::SessionMatchers
  def _verify_current_path(path, options); end
  def assert_current_path(path, options = nil); end
  def assert_no_current_path(path, options = nil); end
  def has_current_path?(path, options = nil); end
  def has_no_current_path?(path, options = nil); end
end
class Capybara::Session
  def _find_frame(*args); end
  def _switch_to_window(window = nil, options = nil); end
  def accept_alert(text_or_options = nil, options = nil, &blk); end
  def accept_confirm(text_or_options = nil, options = nil, &blk); end
  def accept_modal(type, text_or_options, options, &blk); end
  def accept_prompt(text_or_options = nil, options = nil, &blk); end
  def all(*args, &block); end
  def app; end
  def assert_all_of_selectors(*args, &block); end
  def assert_no_selector(*args, &block); end
  def assert_no_text(*args, &block); end
  def assert_no_title(*args, &block); end
  def assert_none_of_selectors(*args, &block); end
  def assert_selector(*args, &block); end
  def assert_text(*args, &block); end
  def assert_title(*args, &block); end
  def attach_file(*args, &block); end
  def body; end
  def check(*args, &block); end
  def choose(*args, &block); end
  def cleanup!; end
  def click_button(*args, &block); end
  def click_link(*args, &block); end
  def click_link_or_button(*args, &block); end
  def click_on(*args, &block); end
  def config; end
  def configure; end
  def current_host; end
  def current_path; end
  def current_scope; end
  def current_url; end
  def current_window; end
  def default_fn(extension); end
  def dismiss_confirm(text_or_options = nil, options = nil, &blk); end
  def dismiss_modal(type, text_or_options, options, &blk); end
  def dismiss_prompt(text_or_options = nil, options = nil, &blk); end
  def document; end
  def driver; end
  def element_script_result(arg); end
  def evaluate_async_script(script, *args); end
  def evaluate_script(script, *args); end
  def execute_script(script, *args); end
  def field_labeled(*args, &block); end
  def fill_in(*args, &block); end
  def find(*args, &block); end
  def find_all(*args, &block); end
  def find_button(*args, &block); end
  def find_by_id(*args, &block); end
  def find_field(*args, &block); end
  def find_link(*args, &block); end
  def first(*args, &block); end
  def go_back; end
  def go_forward; end
  def has_button?(*args, &block); end
  def has_checked_field?(*args, &block); end
  def has_content?(*args, &block); end
  def has_css?(*args, &block); end
  def has_field?(*args, &block); end
  def has_link?(*args, &block); end
  def has_no_button?(*args, &block); end
  def has_no_checked_field?(*args, &block); end
  def has_no_content?(*args, &block); end
  def has_no_css?(*args, &block); end
  def has_no_field?(*args, &block); end
  def has_no_link?(*args, &block); end
  def has_no_select?(*args, &block); end
  def has_no_selector?(*args, &block); end
  def has_no_table?(*args, &block); end
  def has_no_text?(*args, &block); end
  def has_no_title?(*args, &block); end
  def has_no_unchecked_field?(*args, &block); end
  def has_no_xpath?(*args, &block); end
  def has_select?(*args, &block); end
  def has_selector?(*args, &block); end
  def has_table?(*args, &block); end
  def has_text?(*args, &block); end
  def has_title?(*args, &block); end
  def has_unchecked_field?(*args, &block); end
  def has_xpath?(*args, &block); end
  def html; end
  def initialize(mode, app = nil); end
  def inspect; end
  def modal_options(text_or_options, options); end
  def mode; end
  def open_file(path); end
  def open_new_window; end
  def prepare_path(path, extension); end
  def query(*args, &block); end
  def raise_server_error!; end
  def refresh; end
  def refute_selector(*args, &block); end
  def reset!; end
  def reset_session!; end
  def resolve(*args, &block); end
  def response_headers; end
  def save_and_open_page(path = nil); end
  def save_and_open_screenshot(path = nil, options = nil); end
  def save_page(path = nil); end
  def save_screenshot(path = nil, options = nil); end
  def scopes; end
  def select(*args, &block); end
  def self.instance_created?; end
  def server; end
  def source; end
  def status_code; end
  def switch_to_frame(frame); end
  def switch_to_window(window = nil, options = nil, &window_locator); end
  def synchronized; end
  def synchronized=(arg0); end
  def text(*args, &block); end
  def title(*args, &block); end
  def uncheck(*args, &block); end
  def unselect(*args, &block); end
  def using_wait_time(seconds); end
  def visit(visit_uri); end
  def window_opened_by(options = nil, &block); end
  def windows; end
  def within(*args); end
  def within_element(*args); end
  def within_fieldset(locator); end
  def within_frame(*args); end
  def within_table(locator); end
  def within_window(window_or_handle); end
  include Capybara::SessionMatchers
end
class Capybara::Window
  def ==(other); end
  def close; end
  def closed?; end
  def current?; end
  def eql?(other); end
  def exists?; end
  def handle; end
  def hash; end
  def initialize(session, handle); end
  def inspect; end
  def maximize; end
  def raise_unless_current(what); end
  def resize_to(width, height); end
  def session; end
  def size; end
  def wait_for_stable_size(seconds = nil); end
end
class Capybara::Server
  def app; end
  def boot; end
  def error; end
  def find_available_port(host); end
  def host; end
  def initialize(app, port = nil, host = nil, server_errors = nil); end
  def middleware; end
  def pending_requests?; end
  def port; end
  def port_key; end
  def reset_error!; end
  def responsive?; end
  def self.ports; end
  def wait_for_pending_requests; end
end
class Capybara::Server::Middleware
  def call(env); end
  def error; end
  def error=(arg0); end
  def initialize(app, server_errors); end
  def pending_requests?; end
end
class Capybara::Server::Middleware::Counter
  def decrement; end
  def increment; end
  def initialize; end
  def value; end
end
class Capybara::Selector
  def call(locator, options = nil); end
  def css(*expression_filters, &block); end
  def custom_filters; end
  def default_visibility(fallback = nil); end
  def describe(&block); end
  def describe_all_expression_filters(opts = nil); end
  def description(options = nil); end
  def expression_filter(name, *types_and_options, &block); end
  def expression_filters; end
  def filter(name, *types_and_options, &block); end
  def filter_set(name, filters_to_use = nil); end
  def find_by_attr(attribute, value); end
  def find_by_class_attr(classes); end
  def format; end
  def initialize(name, &block); end
  def label(label = nil); end
  def locate_field(xpath, locator, options = nil); end
  def match(&block); end
  def match?(locator); end
  def name; end
  def node_filters; end
  def self.add(name, &block); end
  def self.all; end
  def self.const_missing(const_name); end
  def self.remove(name); end
  def self.update(name, &block); end
  def visible(default_visibility); end
  def xpath(*expression_filters, &block); end
end
module Capybara::Selector::Filters
end
class Capybara::Selector::Filters::Base
  def default; end
  def default?; end
  def initialize(name, block, options = nil); end
  def skip?(value); end
  def valid_value?(value); end
end
class Capybara::Selector::Filters::NodeFilter < Capybara::Selector::Filters::Base
  def matches?(node, value); end
end
class Capybara::Selector::Filters::ExpressionFilter < Capybara::Selector::Filters::Base
  def apply_filter(expr, value); end
end
class Capybara::Selector::Filters::IdentityExpressionFilter < Capybara::Selector::Filters::ExpressionFilter
  def apply_filter(expr, _value); end
  def default?; end
  def initialize; end
end
class Capybara::Selector::FilterSet
  def add_filter(name, filter_class, *types_and_options, &block); end
  def describe(&block); end
  def description(options = nil); end
  def descriptions; end
  def expression_filter(name, *types_and_options, &block); end
  def expression_filters; end
  def filter(name, *types_and_options, &block); end
  def filters; end
  def initialize(name, &block); end
  def node_filters; end
  def self.add(name, &block); end
  def self.all; end
  def self.remove(name); end
end
class Capybara::Selector::CSS
  def self.escape(str); end
  def self.escape_char(c); end
end
module XPath
end
class XPath::Renderer
end
class Capybara::Result
  def [](*args); end
  def at(*args); end
  def each(&block); end
  def empty?; end
  def failure_message; end
  def full_results; end
  def index(*arg0); end
  def initialize(elements, query); end
  def inspect(*args, &block); end
  def last(*args, &block); end
  def lazy_select_elements(&block); end
  def length(*args, &block); end
  def matches_count?; end
  def negative_failure_message; end
  def rest; end
  def sample(*args, &block); end
  def size(*args, &block); end
  def values_at(*args, &block); end
  extend Forwardable
  include Enumerable
end
module Capybara::Queries
end
class Capybara::Queries::BaseQuery
  def assert_valid_keys; end
  def count_message; end
  def expects_none?; end
  def failure_message; end
  def initialize(options); end
  def matches_count?(count); end
  def negative_failure_message; end
  def options; end
  def self.wait(options, default = nil); end
  def session_options; end
  def session_options=(arg0); end
  def wait; end
end
class Capybara::Queries::SelectorQuery < Capybara::Queries::BaseQuery
  def apply_expression_filters(expr); end
  def assert_valid_keys; end
  def css; end
  def custom_keys; end
  def describe_within?; end
  def description; end
  def exact?; end
  def exact_text; end
  def expression; end
  def expression=(arg0); end
  def expression_filters; end
  def filtered_css(expr); end
  def filtered_xpath(expr); end
  def find; end
  def find=(arg0); end
  def initialize(*args, &filter_block); end
  def label; end
  def locator; end
  def locator=(arg0); end
  def match; end
  def matches_filters?(node); end
  def name; end
  def negative; end
  def negative=(arg0); end
  def node_filters; end
  def options; end
  def options=(arg0); end
  def resolve_for(node, exact = nil); end
  def selector; end
  def selector=(arg0); end
  def supports_exact?; end
  def valid_keys; end
  def visible; end
  def warn_exact_usage; end
  def xpath(exact = nil); end
end
class Capybara::Queries::TextQuery < Capybara::Queries::BaseQuery
  def build_message(report_on_invisible); end
  def check_visible_text?; end
  def description; end
  def exact?; end
  def failure_message; end
  def initialize(*args); end
  def negative_failure_message; end
  def resolve_for(node); end
  def text(node, query_type); end
  def valid_keys; end
end
class Capybara::Queries::TitleQuery < Capybara::Queries::BaseQuery
  def failure_message; end
  def failure_message_helper(negated = nil); end
  def initialize(expected_title, options = nil); end
  def negative_failure_message; end
  def resolves_for?(node); end
  def valid_keys; end
end
class Capybara::Queries::CurrentPathQuery < Capybara::Queries::BaseQuery
  def assert_valid_keys; end
  def failure_message; end
  def failure_message_helper(negated = nil); end
  def initialize(expected_path, options = nil); end
  def negative_failure_message; end
  def resolves_for?(session); end
  def valid_keys; end
end
class Capybara::Queries::MatchQuery < Capybara::Queries::SelectorQuery
  def valid_keys; end
  def visible; end
end
class Capybara::Queries::AncestorQuery < Capybara::Queries::MatchQuery
  def description; end
  def resolve_for(node, exact = nil); end
end
class Capybara::Queries::SiblingQuery < Capybara::Queries::MatchQuery
  def description; end
  def resolve_for(node, exact = nil); end
end
module Capybara::Node
end
module Capybara::Node::Finders
  def all(*args, &optional_filter_block); end
  def ancestor(*args, &optional_filter_block); end
  def field_labeled(locator = nil, options = nil, &optional_filter_block); end
  def find(*args, &optional_filter_block); end
  def find_all(*args, &optional_filter_block); end
  def find_button(locator = nil, options = nil, &optional_filter_block); end
  def find_by_id(id, options = nil, &optional_filter_block); end
  def find_field(locator = nil, options = nil, &optional_filter_block); end
  def find_link(locator = nil, options = nil, &optional_filter_block); end
  def first(*args, &optional_filter_block); end
  def sibling(*args, &optional_filter_block); end
  def synced_resolve(query); end
end
module Capybara::Node::Matchers
  def ==(other); end
  def _set_query_session_options(query_args); end
  def _verify_match_result(query_args, optional_filter_block, &result_block); end
  def _verify_selector_result(query_args, optional_filter_block, &result_block); end
  def _verify_text(query_args); end
  def assert_all_of_selectors(*args, &optional_filter_block); end
  def assert_matches_selector(*args, &optional_filter_block); end
  def assert_no_selector(*args, &optional_filter_block); end
  def assert_no_text(*args); end
  def assert_none_of_selectors(*args, &optional_filter_block); end
  def assert_not_matches_selector(*args, &optional_filter_block); end
  def assert_selector(*args, &optional_filter_block); end
  def assert_text(*args); end
  def has_button?(locator = nil, options = nil, &optional_filter_block); end
  def has_checked_field?(locator = nil, options = nil, &optional_filter_block); end
  def has_content?(*args); end
  def has_css?(path, options = nil, &optional_filter_block); end
  def has_field?(locator = nil, options = nil, &optional_filter_block); end
  def has_link?(locator = nil, options = nil, &optional_filter_block); end
  def has_no_button?(locator = nil, options = nil, &optional_filter_block); end
  def has_no_checked_field?(locator = nil, options = nil, &optional_filter_block); end
  def has_no_content?(*args); end
  def has_no_css?(path, options = nil, &optional_filter_block); end
  def has_no_field?(locator = nil, options = nil, &optional_filter_block); end
  def has_no_link?(locator = nil, options = nil, &optional_filter_block); end
  def has_no_select?(locator = nil, options = nil, &optional_filter_block); end
  def has_no_selector?(*args, &optional_filter_block); end
  def has_no_table?(locator = nil, options = nil, &optional_filter_block); end
  def has_no_text?(*args); end
  def has_no_unchecked_field?(locator = nil, options = nil, &optional_filter_block); end
  def has_no_xpath?(path, options = nil, &optional_filter_block); end
  def has_select?(locator = nil, options = nil, &optional_filter_block); end
  def has_selector?(*args, &optional_filter_block); end
  def has_table?(locator = nil, options = nil, &optional_filter_block); end
  def has_text?(*args); end
  def has_unchecked_field?(locator = nil, options = nil, &optional_filter_block); end
  def has_xpath?(path, options = nil, &optional_filter_block); end
  def matches_css?(css, options = nil, &optional_filter_block); end
  def matches_selector?(*args, &optional_filter_block); end
  def matches_xpath?(xpath, options = nil, &optional_filter_block); end
  def not_matches_css?(css, options = nil, &optional_filter_block); end
  def not_matches_selector?(*args, &optional_filter_block); end
  def not_matches_xpath?(xpath, options = nil, &optional_filter_block); end
  def refute_matches_selector(*args, &optional_filter_block); end
  def refute_selector(*args, &optional_filter_block); end
end
module Capybara::Node::Actions
  def _check_with_label(selector, checked, locator, options); end
  def _reset_style(element); end
  def _update_style(element, style); end
  def attach_file(locator, path, options = nil); end
  def check(locator, options = nil); end
  def choose(locator, options = nil); end
  def click_button(locator = nil, options = nil); end
  def click_link(locator = nil, options = nil); end
  def click_link_or_button(locator = nil, options = nil); end
  def click_on(locator = nil, options = nil); end
  def fill_in(locator, options = nil); end
  def select(value, options = nil); end
  def uncheck(locator, options = nil); end
  def unselect(value, options = nil); end
end
module Capybara::Node::DocumentMatchers
  def _verify_title(title, options); end
  def assert_no_title(title, options = nil); end
  def assert_title(title, options = nil); end
  def has_no_title?(title, options = nil); end
  def has_title?(title, options = nil); end
end
class Capybara::Node::Simple
  def [](name); end
  def allow_reload!; end
  def checked?; end
  def disabled?; end
  def find_css(css); end
  def find_xpath(xpath); end
  def initialize(native); end
  def inspect; end
  def native; end
  def path; end
  def selected?; end
  def session_options; end
  def synchronize(seconds = nil); end
  def tag_name; end
  def text(type = nil); end
  def title; end
  def value; end
  def visible?(check_ancestors = nil); end
  include Capybara::Node::DocumentMatchers
  include Capybara::Node::Finders
  include Capybara::Node::Matchers
end
class Capybara::Node::Base
  def base; end
  def catch_error?(error, errors = nil); end
  def driver; end
  def find_css(css); end
  def find_xpath(xpath); end
  def initialize(session, base); end
  def parent; end
  def query_scope; end
  def reload; end
  def session; end
  def session_options; end
  def synchronize(seconds = nil, options = nil); end
  include Capybara::Node::Actions
  include Capybara::Node::Finders
  include Capybara::Node::Matchers
end
class Capybara::Node::Element < Capybara::Node::Base
  def [](attribute); end
  def allow_reload!; end
  def checked?; end
  def click; end
  def disabled?; end
  def double_click; end
  def drag_to(node); end
  def hover; end
  def initialize(session, base, query_scope, query); end
  def inspect; end
  def multiple?; end
  def native; end
  def path; end
  def readonly?; end
  def reload; end
  def right_click; end
  def select_option; end
  def selected?; end
  def send_keys(*args); end
  def set(value, options = nil); end
  def tag_name; end
  def text(type = nil); end
  def trigger(event); end
  def unselect_option; end
  def value; end
  def visible?; end
end
class Capybara::Node::Document < Capybara::Node::Base
  def inspect; end
  def text(type = nil); end
  def title; end
  include Capybara::Node::DocumentMatchers
end
class Capybara::Driver::Base
  def accept_modal(type, options = nil, &blk); end
  def browser_initialized?; end
  def close_window(handle); end
  def current_url; end
  def current_window_handle; end
  def dismiss_modal(type, options = nil, &blk); end
  def evaluate_async_script(script, *args); end
  def evaluate_script(script, *args); end
  def execute_script(script, *args); end
  def find_css(query); end
  def find_xpath(query); end
  def go_back; end
  def go_forward; end
  def html; end
  def invalid_element_errors; end
  def maximize_window(handle); end
  def needs_server?; end
  def no_such_window_error; end
  def open_new_window; end
  def refresh; end
  def reset!; end
  def resize_window_to(handle, width, height); end
  def response_headers; end
  def save_screenshot(path, options = nil); end
  def session=(arg0); end
  def session_options; end
  def status_code; end
  def switch_to_frame(frame); end
  def switch_to_window(handle); end
  def visit(path); end
  def wait?; end
  def window_handles; end
  def window_size(handle); end
  def within_window(locator); end
end
module Capybara::Driver
end
class Capybara::Driver::Node
  def ==(other); end
  def [](name); end
  def all_text; end
  def checked?; end
  def click; end
  def disabled?; end
  def double_click; end
  def drag_to(element); end
  def driver; end
  def hover; end
  def initialize(driver, native); end
  def inspect; end
  def multiple?; end
  def native; end
  def path; end
  def readonly?; end
  def right_click; end
  def select_option; end
  def selected?; end
  def send_keys(*args); end
  def set(value, options = nil); end
  def tag_name; end
  def trigger(event); end
  def unselect_option; end
  def value; end
  def visible?; end
  def visible_text; end
end
class Capybara::RackTest::Driver < Capybara::Driver::Base
  def app; end
  def browser; end
  def browser_initialized?; end
  def current_url; end
  def delete(*args, &block); end
  def dom; end
  def find_css(selector); end
  def find_xpath(selector); end
  def follow(method, path, attributes = nil); end
  def follow_redirects?; end
  def get(*args, &block); end
  def header(key, value); end
  def html; end
  def initialize(app, options = nil); end
  def options; end
  def post(*args, &block); end
  def put(*args, &block); end
  def redirect_limit; end
  def refresh; end
  def request; end
  def reset!; end
  def response; end
  def response_headers; end
  def status_code; end
  def submit(method, path, attributes); end
  def title; end
  def visit(path, attributes = nil); end
end
class Capybara::RackTest::Node < Capybara::Driver::Node
  def ==(other); end
  def [](name); end
  def all_text; end
  def attribute_is_not_blank?(attribute); end
  def checkbox?; end
  def checked?; end
  def click; end
  def disabled?; end
  def find_css(locator); end
  def find_xpath(locator); end
  def form; end
  def input_field?; end
  def path; end
  def radio?; end
  def select_node; end
  def select_option; end
  def selected?; end
  def set(value); end
  def set_checkbox(value); end
  def set_input(value); end
  def set_radio(_value); end
  def string_node; end
  def tag_name; end
  def text_or_password?; end
  def textarea?; end
  def type; end
  def unnormalized_text(check_ancestor_visibility = nil); end
  def unselect_option; end
  def value; end
  def visible?; end
  def visible_text; end
end
class Capybara::RackTest::Form < Capybara::RackTest::Node
  def make_params; end
  def merge_param!(params, key, value); end
  def multipart?; end
  def params(button); end
  def request_method; end
  def submit(button); end
end
class Capybara::RackTest::Form::NilUploadedFile < Rack::Test::UploadedFile
  def content_type; end
  def initialize; end
  def original_filename; end
  def path; end
  def read; end
  def size; end
end
class Capybara::RackTest::Form::ParamsHash < Hash
  def to_params_hash; end
end
class Capybara::RackTest::Browser
  def app; end
  def build_rack_mock_session; end
  def current_host; end
  def current_host=(arg0); end
  def current_url; end
  def dom; end
  def driver; end
  def find(format, selector); end
  def follow(method, path, attributes = nil); end
  def html; end
  def initialize(driver); end
  def options; end
  def process(method, path, attributes = nil, env = nil); end
  def process_and_follow_redirects(method, path, attributes = nil, env = nil); end
  def refresh; end
  def request_path; end
  def reset_cache!; end
  def reset_host!; end
  def submit(method, path, attributes); end
  def title; end
  def visit(path, attributes = nil); end
  include Rack::Test::Methods
end
class Capybara::RackTest::CSSHandlers < BasicObject
  def disabled(list); end
  def enabled(list); end
  include Kernel
end
class Capybara::Selenium::Node < Capybara::Driver::Node
  def ==(other); end
  def [](name); end
  def all_text; end
  def checked?; end
  def click; end
  def content_editable?; end
  def disabled?; end
  def double_click; end
  def drag_to(element); end
  def find_css(locator); end
  def find_xpath(locator); end
  def hover; end
  def multiple?; end
  def path; end
  def readonly?; end
  def right_click; end
  def scroll_if_needed(&block); end
  def select_node; end
  def select_option; end
  def selected?; end
  def send_keys(*args); end
  def set(value, options = nil); end
  def set_text(value, options); end
  def tag_name; end
  def unselect_option; end
  def value; end
  def visible?; end
  def visible_text; end
end
class Capybara::Selenium::Driver < Capybara::Driver::Base
  def accept_modal(_type, options = nil); end
  def app; end
  def browser; end
  def browser_initialized?; end
  def browser_name; end
  def chrome?; end
  def close_window(handle); end
  def current_url; end
  def current_window_handle; end
  def dismiss_modal(_type, options = nil); end
  def evaluate_async_script(script, *args); end
  def evaluate_script(script, *args); end
  def execute_script(script, *args); end
  def find_css(selector); end
  def find_headless_modal(options = nil); end
  def find_modal(options = nil); end
  def find_window(locator); end
  def find_xpath(selector); end
  def firefox?; end
  def go_back; end
  def go_forward; end
  def html; end
  def initialize(app, options = nil); end
  def insert_modal_handlers(accept, response_text); end
  def invalid_element_errors; end
  def load_selenium; end
  def marionette?; end
  def maximize_window(handle); end
  def modal_error; end
  def needs_server?; end
  def no_such_window_error; end
  def open_new_window; end
  def options; end
  def quit; end
  def refresh; end
  def reset!; end
  def resize_window_to(handle, width, height); end
  def save_screenshot(path, _options = nil); end
  def silenced_unknown_error_message?(msg); end
  def silenced_unknown_error_messages; end
  def switch_to_frame(frame); end
  def switch_to_window(handle); end
  def title; end
  def unwrap_script_result(arg); end
  def visit(path); end
  def wait?; end
  def window_handles; end
  def window_size(handle); end
  def within_given_window(handle); end
  def within_window(locator); end
end
class Capybara::CapybaraError < StandardError
end
class Capybara::DriverNotFoundError < Capybara::CapybaraError
end
class Capybara::FrozenInTime < Capybara::CapybaraError
end
class Capybara::ElementNotFound < Capybara::CapybaraError
end
class Capybara::ModalNotFound < Capybara::CapybaraError
end
class Capybara::Ambiguous < Capybara::ElementNotFound
end
class Capybara::ExpectationNotMet < Capybara::ElementNotFound
end
class Capybara::FileNotFound < Capybara::CapybaraError
end
class Capybara::UnselectNotAllowed < Capybara::CapybaraError
end
class Capybara::NotSupportedByDriverError < Capybara::CapybaraError
end
class Capybara::InfiniteRedirectError < Capybara::CapybaraError
end
class Capybara::ScopeError < Capybara::CapybaraError
end
class Capybara::WindowError < Capybara::CapybaraError
end
class Capybara::ReadOnlyElementError < Capybara::CapybaraError
end
module Capybara::RackTest
end
module Capybara::Selenium
end
module Capybara::DSL
  def accept_alert(*args, &block); end
  def accept_confirm(*args, &block); end
  def accept_prompt(*args, &block); end
  def all(*args, &block); end
  def assert_all_of_selectors(*args, &block); end
  def assert_current_path(*args, &block); end
  def assert_no_current_path(*args, &block); end
  def assert_no_selector(*args, &block); end
  def assert_no_text(*args, &block); end
  def assert_no_title(*args, &block); end
  def assert_none_of_selectors(*args, &block); end
  def assert_selector(*args, &block); end
  def assert_text(*args, &block); end
  def assert_title(*args, &block); end
  def attach_file(*args, &block); end
  def body(*args, &block); end
  def check(*args, &block); end
  def choose(*args, &block); end
  def click_button(*args, &block); end
  def click_link(*args, &block); end
  def click_link_or_button(*args, &block); end
  def click_on(*args, &block); end
  def current_host(*args, &block); end
  def current_path(*args, &block); end
  def current_scope(*args, &block); end
  def current_url(*args, &block); end
  def current_window(*args, &block); end
  def dismiss_confirm(*args, &block); end
  def dismiss_prompt(*args, &block); end
  def evaluate_script(*args, &block); end
  def execute_script(*args, &block); end
  def field_labeled(*args, &block); end
  def fill_in(*args, &block); end
  def find(*args, &block); end
  def find_all(*args, &block); end
  def find_button(*args, &block); end
  def find_by_id(*args, &block); end
  def find_field(*args, &block); end
  def find_link(*args, &block); end
  def first(*args, &block); end
  def go_back(*args, &block); end
  def go_forward(*args, &block); end
  def has_button?(*args, &block); end
  def has_checked_field?(*args, &block); end
  def has_content?(*args, &block); end
  def has_css?(*args, &block); end
  def has_current_path?(*args, &block); end
  def has_field?(*args, &block); end
  def has_link?(*args, &block); end
  def has_no_button?(*args, &block); end
  def has_no_checked_field?(*args, &block); end
  def has_no_content?(*args, &block); end
  def has_no_css?(*args, &block); end
  def has_no_current_path?(*args, &block); end
  def has_no_field?(*args, &block); end
  def has_no_link?(*args, &block); end
  def has_no_select?(*args, &block); end
  def has_no_selector?(*args, &block); end
  def has_no_table?(*args, &block); end
  def has_no_text?(*args, &block); end
  def has_no_title?(*args, &block); end
  def has_no_unchecked_field?(*args, &block); end
  def has_no_xpath?(*args, &block); end
  def has_select?(*args, &block); end
  def has_selector?(*args, &block); end
  def has_table?(*args, &block); end
  def has_text?(*args, &block); end
  def has_title?(*args, &block); end
  def has_unchecked_field?(*args, &block); end
  def has_xpath?(*args, &block); end
  def html(*args, &block); end
  def open_new_window(*args, &block); end
  def page; end
  def query(*args, &block); end
  def refresh(*args, &block); end
  def refute_selector(*args, &block); end
  def reset_session!(*args, &block); end
  def resolve(*args, &block); end
  def response_headers(*args, &block); end
  def save_and_open_page(*args, &block); end
  def save_and_open_screenshot(*args, &block); end
  def save_page(*args, &block); end
  def save_screenshot(*args, &block); end
  def select(*args, &block); end
  def self.extended(base); end
  def self.included(base); end
  def source(*args, &block); end
  def status_code(*args, &block); end
  def switch_to_frame(*args, &block); end
  def switch_to_window(*args, &block); end
  def text(*args, &block); end
  def title(*args, &block); end
  def uncheck(*args, &block); end
  def unselect(*args, &block); end
  def using_session(name, &block); end
  def using_wait_time(seconds, &block); end
  def visit(*args, &block); end
  def window_opened_by(*args, &block); end
  def windows(*args, &block); end
  def within(*args, &block); end
  def within_element(*args, &block); end
  def within_fieldset(*args, &block); end
  def within_frame(*args, &block); end
  def within_table(*args, &block); end
  def within_window(*args, &block); end
end
module Capybara::RSpecMatchers
  def become_closed(options = nil); end
  def have_all_of_selectors(*args, &optional_filter_block); end
  def have_button(locator = nil, options = nil, &optional_filter_block); end
  def have_checked_field(locator = nil, options = nil, &optional_filter_block); end
  def have_content(*args); end
  def have_css(css, options = nil, &optional_filter_block); end
  def have_current_path(path, options = nil); end
  def have_field(locator = nil, options = nil, &optional_filter_block); end
  def have_link(locator = nil, options = nil, &optional_filter_block); end
  def have_none_of_selectors(*args, &optional_filter_block); end
  def have_select(locator = nil, options = nil, &optional_filter_block); end
  def have_selector(*args, &optional_filter_block); end
  def have_table(locator = nil, options = nil, &optional_filter_block); end
  def have_text(*args); end
  def have_title(title, options = nil); end
  def have_unchecked_field(locator = nil, options = nil, &optional_filter_block); end
  def have_xpath(xpath, options = nil, &optional_filter_block); end
  def match_css(css, options = nil, &optional_filter_block); end
  def match_selector(*args, &optional_filter_block); end
  def match_xpath(xpath, options = nil, &optional_filter_block); end
end
module Capybara::RSpecMatchers::Compound
  def and(matcher); end
  def and_then(matcher); end
  def or(matcher); end
  include RSpec::Matchers::Composable
end
class Capybara::RSpecMatchers::Compound::CapybaraEvaluator
  def initialize(actual, matcher_1, matcher_2); end
  def matcher_matches?(matcher); end
  def reset; end
end
class Capybara::RSpecMatchers::Compound::And < RSpec::Matchers::BuiltIn::Compound::And
  def match(_expected, actual); end
  def sync_element(el); end
end
class Capybara::RSpecMatchers::Compound::Or < RSpec::Matchers::BuiltIn::Compound::Or
  def match(_expected, actual); end
  def sync_element(el); end
end
class Capybara::RSpecMatchers::Matcher
  def failure_message; end
  def failure_message_for_should; end
  def failure_message_for_should_not; end
  def failure_message_when_negated; end
  def session_options; end
  def session_query_args; end
  def wrap(actual); end
  def wrap_does_not_match?(actual); end
  def wrap_matches?(actual); end
  include Capybara::RSpecMatchers::Compound
end
class Capybara::RSpecMatchers::HaveSelector < Capybara::RSpecMatchers::Matcher
  def description; end
  def does_not_match?(actual); end
  def initialize(*args, &filter_block); end
  def matches?(actual); end
  def query; end
end
class Capybara::RSpecMatchers::HaveAllSelectors < Capybara::RSpecMatchers::Matcher
  def description; end
  def does_not_match?(actual); end
  def initialize(*args, &filter_block); end
  def matches?(actual); end
end
class Capybara::RSpecMatchers::HaveNoSelectors < Capybara::RSpecMatchers::Matcher
  def description; end
  def does_not_match?(actual); end
  def initialize(*args, &filter_block); end
  def matches?(actual); end
end
class Capybara::RSpecMatchers::MatchSelector < Capybara::RSpecMatchers::HaveSelector
  def description; end
  def does_not_match?(actual); end
  def matches?(actual); end
  def query; end
end
class Capybara::RSpecMatchers::HaveText < Capybara::RSpecMatchers::Matcher
  def content; end
  def description; end
  def does_not_match?(actual); end
  def format(content); end
  def initialize(*args); end
  def matches?(actual); end
  def options; end
  def type; end
end
class Capybara::RSpecMatchers::HaveTitle < Capybara::RSpecMatchers::Matcher
  def description; end
  def does_not_match?(actual); end
  def initialize(*args); end
  def matches?(actual); end
  def title; end
end
class Capybara::RSpecMatchers::HaveCurrentPath < Capybara::RSpecMatchers::Matcher
  def current_path; end
  def description; end
  def does_not_match?(actual); end
  def initialize(*args); end
  def matches?(actual); end
end
class Capybara::RSpecMatchers::BecomeClosed
  def failure_message; end
  def failure_message_for_should; end
  def failure_message_for_should_not; end
  def failure_message_when_negated; end
  def initialize(options); end
  def matches?(window); end
end
module RSpec::Matchers
  def not_match_selector(*args, &block); end
  def self.included(base); end
end
class RSpec::Core::ExampleGroup
  def self.ffeature(*args, &example_group_block); end
  def self.fscenario(*all_args, &block); end
  def self.xfeature(*args, &example_group_block); end
end
module RSpec
  def self.ffeature(*args, &example_group_block); end
  def self.xfeature(*args, &example_group_block); end
end
class Module
  def ffeature(*a, &b); end
  def xfeature(*a, &b); end
end
module Capybara::RSpecMatcherProxies
  def all(*args); end
  def within(*args); end
end
