# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/capybara-screenshot/all/capybara-screenshot.rbi
#
# capybara-screenshot-0.3.22
module Capybara
end
module Capybara::Screenshot
  def self.append_screenshot_path=(value); end
  def self.append_timestamp; end
  def self.append_timestamp=(arg0); end
  def self.autosave_on_failure; end
  def self.autosave_on_failure=(arg0); end
  def self.capybara_root; end
  def self.filename_prefix_for(test_type, test); end
  def self.filename_prefix_formatters; end
  def self.filename_prefix_formatters=(arg0); end
  def self.register_driver(driver, &block); end
  def self.register_filename_prefix_formatter(test_type, &block); end
  def self.registered_drivers; end
  def self.registered_drivers=(arg0); end
  def self.screen_shot_and_open_image; end
  def self.screen_shot_and_save_page; end
  def self.screenshot_and_open_image; end
  def self.screenshot_and_save_page; end
  def self.webkit_options; end
  def self.webkit_options=(arg0); end
end
class Capybara::Screenshot::Saver
  def capybara; end
  def clear_save_and_open_page_path; end
  def file_base_name; end
  def html_path; end
  def html_saved?; end
  def initialize(capybara, page, html_save = nil, filename_prefix = nil); end
  def output(message); end
  def output_screenshot_path; end
  def page; end
  def save; end
  def save_html; end
  def save_screenshot; end
  def screenshot_path; end
  def screenshot_saved?; end
end
module Capybara::DSL
  def screenshot_and_open_image; end
  def screenshot_and_save_page; end
end
module Capybara::Screenshot::RSpec
  def self.add_link_to_screenshot_for_failed_examples; end
  def self.add_link_to_screenshot_for_failed_examples=(arg0); end
  def self.after_failed_example(example); end
end
module Capybara::Screenshot::RSpec::BaseReporter
  def enhance_with_screenshot(method); end
end
module Capybara::Screenshot::RSpec::TextReporter
  def dump_failure_info_with_screenshot(example); end
  def self.included(mod); end
  extend Capybara::Screenshot::RSpec::BaseReporter
end
module Capybara::Screenshot::RSpec::HtmlLinkReporter
  def attributes_for_screenshot_link(url); end
  def extra_failure_content_with_screenshot(exception); end
  def link_to_screenshot(title, path); end
  def self.included(mod); end
  extend Capybara::Screenshot::RSpec::BaseReporter
end
module Capybara::Screenshot::RSpec::HtmlEmbedReporter
  def extra_failure_content_with_screenshot(exception); end
  def self.included(mod); end
  extend Capybara::Screenshot::RSpec::BaseReporter
end
module Capybara::Screenshot::RSpec::TextMateLinkReporter
  def attributes_for_screenshot_link(url); end
  def self.included(mod); end
  extend Capybara::Screenshot::RSpec::BaseReporter
  include Capybara::Screenshot::RSpec::HtmlLinkReporter
end
