# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cliver/all/cliver.rbi
#
# cliver-0.3.2
class File < IO
  def self.absolute_path?(path, platform = nil); end
end
module Cliver
  def dependency_unmet?(*args, &block); end
  def self.assert(*args, &block); end
  def self.detect!(*args, &block); end
  def self.detect(*args, &block); end
  def self.verify!(executable, *args, &block); end
  extend Cliver
end
class Cliver::Dependency
  def check_compatibility!; end
  def detect!; end
  def detect; end
  def detect_version(executable_path); end
  def executable_description; end
  def filtered_requirement; end
  def find_executables; end
  def initialize(executables, *args, &detector); end
  def installed_versions; end
  def raise_not_found!; end
  def raise_version_mismatch!(installed); end
  def requirement_satisfied_by?(raw_version); end
  def requirements_description; end
  def strict?; end
end
class Cliver::Dependency::NotMet < ArgumentError
end
class Cliver::Dependency::VersionMismatch < Cliver::Dependency::NotMet
end
class Cliver::Dependency::NotFound < Cliver::Dependency::NotMet
end
class Cliver::ShellCapture
  def command_found; end
  def initialize(command); end
  def stderr; end
  def stdout; end
end
class Anonymous_Struct_26 < Struct
  def command_arg; end
  def command_arg=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
  def version_pattern; end
  def version_pattern=(_); end
end
class Cliver::Detector < Anonymous_Struct_26
  def command_arg; end
  def detect_version(executable_path); end
  def initialize(*args); end
  def self.generate(detector_argument); end
  def to_proc; end
  def version_command(executable_path); end
  def version_pattern; end
end
module Cliver::Filter
  def apply(version); end
  def requirements(requirements); end
end
