# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/colored/all/colored.rbi
#
# colored-1.2
module Colored
  def black; end
  def black_on_blue; end
  def black_on_cyan; end
  def black_on_green; end
  def black_on_magenta; end
  def black_on_red; end
  def black_on_white; end
  def black_on_yellow; end
  def blue; end
  def blue_on_black; end
  def blue_on_cyan; end
  def blue_on_green; end
  def blue_on_magenta; end
  def blue_on_red; end
  def blue_on_white; end
  def blue_on_yellow; end
  def bold; end
  def color(color_name); end
  def colorize(string, options = nil); end
  def colors; end
  def cyan; end
  def cyan_on_black; end
  def cyan_on_blue; end
  def cyan_on_green; end
  def cyan_on_magenta; end
  def cyan_on_red; end
  def cyan_on_white; end
  def cyan_on_yellow; end
  def extra(extra_name); end
  def green; end
  def green_on_black; end
  def green_on_blue; end
  def green_on_cyan; end
  def green_on_magenta; end
  def green_on_red; end
  def green_on_white; end
  def green_on_yellow; end
  def magenta; end
  def magenta_on_black; end
  def magenta_on_blue; end
  def magenta_on_cyan; end
  def magenta_on_green; end
  def magenta_on_red; end
  def magenta_on_white; end
  def magenta_on_yellow; end
  def on_black; end
  def on_blue; end
  def on_cyan; end
  def on_green; end
  def on_magenta; end
  def on_red; end
  def on_white; end
  def on_yellow; end
  def red; end
  def red_on_black; end
  def red_on_blue; end
  def red_on_cyan; end
  def red_on_green; end
  def red_on_magenta; end
  def red_on_white; end
  def red_on_yellow; end
  def reversed; end
  def to_eol; end
  def underline; end
  def white; end
  def white_on_black; end
  def white_on_blue; end
  def white_on_cyan; end
  def white_on_green; end
  def white_on_magenta; end
  def white_on_red; end
  def white_on_yellow; end
  def yellow; end
  def yellow_on_black; end
  def yellow_on_blue; end
  def yellow_on_cyan; end
  def yellow_on_green; end
  def yellow_on_magenta; end
  def yellow_on_red; end
  def yellow_on_white; end
  extend Colored
end
class String
  include Colored
end
