# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/fakefs/all/fakefs.rbi
#
# fakefs-0.9.1
class Object < BasicObject
  def FakeFS(&block); end
  def Pathname(*args); end
  def RealPathname(*args); end
end
module FakeFS
  def self.activate!; end
  def self.activated?; end
  def self.deactivate!; end
  def self.with; end
  def self.without; end
  def use_fakefs(describe_block, opts); end
end
class FakeFS::FakeFile
  def atime; end
  def atime=(arg0); end
  def birthtime; end
  def clone(parent = nil); end
  def content; end
  def content=(str); end
  def ctime; end
  def delete; end
  def entry; end
  def gid; end
  def gid=(arg0); end
  def initialize(name = nil, parent = nil); end
  def inode; end
  def inode=(arg0); end
  def inspect; end
  def link(other_file); end
  def links; end
  def mode; end
  def mode=(arg0); end
  def mtime; end
  def mtime=(arg0); end
  def name; end
  def name=(arg0); end
  def parent; end
  def parent=(arg0); end
  def to_s; end
  def uid; end
  def uid=(arg0); end
end
class FakeFS::FakeFile::Inode
  def clone; end
  def content; end
  def content=(arg0); end
  def initialize(file_owner); end
  def link(file); end
  def links; end
  def links=(arg0); end
  def unlink(file); end
end
class FakeFS::FakeDir
  def [](name); end
  def []=(name, value); end
  def atime; end
  def atime=(arg0); end
  def clone(parent = nil); end
  def content; end
  def ctime; end
  def delete(node = nil); end
  def empty?; end
  def entries; end
  def entry; end
  def gid; end
  def gid=(arg0); end
  def initialize(name = nil, parent = nil); end
  def inspect; end
  def matches(pattern); end
  def mode; end
  def mode=(arg0); end
  def mtime; end
  def mtime=(arg0); end
  def name; end
  def name=(arg0); end
  def parent; end
  def parent=(arg0); end
  def to_s; end
  def uid; end
  def uid=(arg0); end
end
class FakeFS::FakeSymlink
  def delete; end
  def entry; end
  def initialize(target); end
  def inspect; end
  def method_missing(*args, &block); end
  def name; end
  def name=(arg0); end
  def parent; end
  def parent=(arg0); end
  def respond_to?(method, include_private = nil); end
  def target; end
  def target=(arg0); end
  def to_s; end
end
module FakeFS::FileSystem
  def add(path, object = nil); end
  def assert_dir(dir); end
  def chdir(dir, &blk); end
  def clear; end
  def clone(path, target = nil); end
  def current_dir; end
  def delete(path); end
  def dir_levels; end
  def directories_under(dir); end
  def files; end
  def find(path); end
  def find_recurser(dir, parts); end
  def fs; end
  def normalize_path(path); end
  def path_parts(path); end
  extend FakeFS::FileSystem
end
module FakeFS::FileUtils
  def cd(dir, &block); end
  def chdir(dir, &block); end
  def chmod(mode, list, _options = nil); end
  def chmod_R(mode, list, _options = nil); end
  def chown(user, group, list, _options = nil); end
  def chown_R(user, group, list, _options = nil); end
  def cmp(file1, file2); end
  def compare_file(file1, file2); end
  def copy(src, dest, options = nil); end
  def copy_file(src, dest, _preserve = nil, _dereference = nil); end
  def cp(src, dest, options = nil); end
  def cp_r(src, dest, options = nil); end
  def identical?(file1, file2); end
  def ln_s(target, path, options = nil); end
  def ln_sf(target, path); end
  def makedirs(list, options = nil); end
  def mkdir(list, _ignored_options = nil); end
  def mkdir_p(list, options = nil); end
  def mkpath(list, options = nil); end
  def move(src, dest, options = nil); end
  def mv(src, dest, options = nil); end
  def remove(list, options = nil); end
  def remove_entry_secure(list, options = nil); end
  def rm(list, options = nil); end
  def rm_f(list, options = nil); end
  def rm_r(list, options = nil); end
  def rm_rf(list, options = nil); end
  def rmdir(list, _options = nil); end
  def rmtree(list, options = nil); end
  def safe_unlink(list, options = nil); end
  def symlink(target, path, options = nil); end
  def touch(list, options = nil); end
  def uptodate?(new, old_list); end
  extend FakeFS::FileUtils
end
class FakeFS::File < StringIO
  def advise(_advice, _offset = nil, _len = nil); end
  def atime; end
  def autoclose; end
  def autoclose=(arg0); end
  def autoclose?; end
  def binary_mode?; end
  def binmode?; end
  def birthtime; end
  def check_file_existence!; end
  def check_modes!; end
  def chmod(mode_int); end
  def chown(owner_int, group_int); end
  def close_on_exec=(_bool); end
  def close_on_exec?; end
  def create_missing_file; end
  def ctime; end
  def exists?; end
  def fdatasync; end
  def file_creation_mode?; end
  def flock(*arg0); end
  def initialize(path, mode = nil, _perm = nil); end
  def ioctl(*arg0); end
  def is_a?(klass); end
  def lstat; end
  def mode_in?(list); end
  def mode_in_bitmask?(mask); end
  def mtime; end
  def path; end
  def read(length = nil, buf = nil); end
  def read_nonblock; end
  def readpartial(*arg0); end
  def self.absolute_path(file_name, dir_name = nil); end
  def self.atime(path); end
  def self.basename(*args); end
  def self.binread(file, length = nil, offset = nil); end
  def self.birthtime(path); end
  def self.chmod(mode_int, filename); end
  def self.chown(owner_int, group_int, filename); end
  def self.const_missing(name); end
  def self.ctime(path); end
  def self.delete(*file_names); end
  def self.directory?(path); end
  def self.dirname(path); end
  def self.executable?(filename); end
  def self.exist?(path); end
  def self.exists?(path); end
  def self.expand_path(file_name, dir_string = nil); end
  def self.extname(path); end
  def self.file?(path); end
  def self.fnmatch(pattern, path, flags = nil); end
  def self.fnmatch?(pattern, path, flags = nil); end
  def self.foreach(path, *args, &block); end
  def self.ftype(filename); end
  def self.join(*parts); end
  def self.link(source, dest); end
  def self.lstat(file); end
  def self.mtime(path); end
  def self.path(file); end
  def self.read(path, *args); end
  def self.readable?(path); end
  def self.readlines(path); end
  def self.readlink(path); end
  def self.realdirpath(*args); end
  def self.realpath(*args); end
  def self.rename(source, dest); end
  def self.size(path); end
  def self.size?(path); end
  def self.split(path); end
  def self.stat(file); end
  def self.sticky?(_path); end
  def self.symlink(source, dest); end
  def self.symlink?(path); end
  def self.umask(*args); end
  def self.unlink(*file_names); end
  def self.utime(atime, mtime, *paths); end
  def self.writable?(path); end
  def self.write(filename, contents, offset = nil, open_args = nil); end
  def self.zero?(path); end
  def size; end
  def stat; end
  def sysread(*arg0); end
  def sysseek(position, whence = nil); end
  def syswrite(str); end
  def tell=(arg0); end
  def to_i; end
  def to_io; end
  def to_path; end
  def write(str); end
  def write_nonblock(*arg0); end
end
class FakeFS::File::Stat
  def <=>(other); end
  def atime; end
  def birthtime; end
  def ctime; end
  def directory?; end
  def file?; end
  def ftype; end
  def gid; end
  def initialize(file, lstat = nil); end
  def mode; end
  def mtime; end
  def nlink; end
  def readable?; end
  def size; end
  def sticky?; end
  def symlink?; end
  def uid; end
  def world_readable?; end
  def world_writable?; end
  def writable?; end
  def zero?; end
  include Comparable
end
module FakeFS::FileTest
  def directory?(file_name); end
  def exist?(file_name); end
  def file?(file_name); end
  def readable?(file_name); end
  def size?(file_name); end
  def writable?(file_name); end
  extend FakeFS::FileTest
end
class FakeFS::Dir
  def close; end
  def each; end
  def entry_to_relative_path(entry); end
  def initialize(string); end
  def path; end
  def pos; end
  def pos=(integer); end
  def read; end
  def rewind; end
  def seek(integer); end
  def self.[](*pattern); end
  def self._check_for_valid_file(path); end
  def self.chdir(dir, &blk); end
  def self.chroot(_string); end
  def self.delete(string); end
  def self.entries(dirname, _opts = nil); end
  def self.exist?(path); end
  def self.exists?(path); end
  def self.foreach(dirname, &_block); end
  def self.getwd; end
  def self.glob(pattern, _flags = nil, &block); end
  def self.home(user = nil); end
  def self.mkdir(string, _integer = nil); end
  def self.mktmpdir(prefix_suffix = nil, tmpdir = nil); end
  def self.open(string, &_block); end
  def self.pwd; end
  def self.rmdir(string); end
  def self.tmpdir; end
  def self.unlink(string); end
  include Enumerable
end
module FakeFS::Dir::Tmpname
  def create(basename, *rest); end
  def make_tmpname(prefix_suffix, n); end
  def self.create(basename, *rest); end
  def self.make_tmpname(prefix_suffix, n); end
  def self.tmpdir; end
  def tmpdir; end
end
module FakeFS::Globber
  def drop_root(path_parts); end
  def each_char_with_levels(string, level_start, level_end); end
  def expand(pattern); end
  def path_components(pattern); end
  def regexp(pattern); end
  extend FakeFS::Globber
end
class FakeFS::Pathname
  def +(other); end
  def <=>(other); end
  def ==(other); end
  def ===(other); end
  def absolute?; end
  def add_trailing_separator(path); end
  def ascend; end
  def atime; end
  def basename(*args); end
  def binread(*args); end
  def blockdev?; end
  def chardev?; end
  def children(with_directory = nil); end
  def chmod(mode); end
  def chop_basename(path); end
  def chown(owner, group); end
  def cleanpath(consider_symlink = nil); end
  def cleanpath_aggressive; end
  def cleanpath_conservative; end
  def ctime; end
  def del_trailing_separator(path); end
  def delete; end
  def descend; end
  def directory?; end
  def dirname; end
  def each_child(with_directory = nil, &b); end
  def each_entry(*arg0); end
  def each_filename; end
  def each_line(*args, &block); end
  def entries; end
  def eql?(other); end
  def executable?; end
  def executable_real?; end
  def exist?; end
  def expand_path(*args); end
  def extname; end
  def file?; end
  def find(*arg0); end
  def fnmatch(pattern, *args); end
  def fnmatch?(pattern, *args); end
  def freeze; end
  def ftype; end
  def grpowned?; end
  def hash; end
  def initialize(path); end
  def inspect; end
  def join(*args); end
  def lchmod(mode); end
  def lchown(owner, group); end
  def lstat; end
  def make_link(old); end
  def make_symlink(old); end
  def mkdir(*args); end
  def mkpath; end
  def mountpoint?; end
  def mtime; end
  def open(*args, &block); end
  def opendir(&block); end
  def owned?; end
  def parent; end
  def pipe?; end
  def plus(path1, path2); end
  def prepend_prefix(prefix, relpath); end
  def read(*args); end
  def readable?; end
  def readable_real?; end
  def readlines(*args); end
  def readlink; end
  def realdirpath(basedir = nil); end
  def realpath(basedir = nil); end
  def relative?; end
  def relative_path_from(base_directory); end
  def rename(to); end
  def rmdir; end
  def rmtree; end
  def root?; end
  def self.getwd; end
  def self.glob(*args); end
  def self.pwd; end
  def setgid?; end
  def setuid?; end
  def size; end
  def size?; end
  def socket?; end
  def split; end
  def split_names(path); end
  def stat; end
  def sticky?; end
  def sub(pattern, *rest, &block); end
  def sub_ext(repl); end
  def symlink?; end
  def sysopen(*_args); end
  def taint; end
  def to_path; end
  def to_s; end
  def trailing_separator?(path); end
  def truncate(length); end
  def unlink; end
  def untaint; end
  def utime(atime, mtime); end
  def world_readable?; end
  def world_writable?; end
  def writable?; end
  def writable_real?; end
  def zero?; end
end
module FakeFS::Kernel
  def self.captives; end
  def self.captives=(arg0); end
  def self.hijack!; end
  def self.hijack(name, &block); end
  def self.unhijack!; end
end
module FakeFS::SpecHelpers
  def self.extended(example_group); end
  def self.included(example_group); end
  include FakeFS
end
module FakeFS::SpecHelpers::All
  def self.extended(example_group); end
  def self.included(example_group); end
  include FakeFS
end
