# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/flamegraph/all/flamegraph.rbi
#
# flamegraph-0.9.5
module Flamegraph
  def self.generate(filename = nil, opts = nil); end
end
class Flamegraph::Renderer
  def embed(*files); end
  def graph_data; end
  def graph_html(embed_resources); end
  def initialize(stacks); end
  def read(file); end
end
class Flamegraph::Sampler
  def self.collect(fidelity = nil); end
end
