# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/guard-teaspoon/all/guard-teaspoon.rbi
#
# guard-teaspoon-0.8.0
module Guard
end
class Guard::Teaspoon < Guard::Plugin
  def add_failed(paths); end
  def failed_paths; end
  def failed_paths=(arg0); end
  def initialize(options = nil); end
  def last_failed; end
  def last_failed=(arg0); end
  def reload; end
  def remove_failed(paths); end
  def resolver; end
  def resolver=(arg0); end
  def run_all; end
  def run_on_modifications(original_paths); end
  def runner; end
  def runner=(arg0); end
  def start; end
end
class Guard::Teaspoon::Resolver
  def initialize(options = nil); end
  def resolve(original_paths); end
  def suites; end
  def suites=(arg0); end
end
class Guard::Teaspoon::Runner
  def abort; end
  def console; end
  def console=(arg0); end
  def initialize(options = nil); end
  def run(files = nil, options = nil); end
  def run_all(options = nil); end
end
