# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/guard-spork/all/guard-spork.rbi
#
# guard-spork-2.1.0
module Guard
end
class Guard::Spork < Guard::Plugin
  def initialize(options = nil); end
  def relaunch_sporks; end
  def reload; end
  def run_on_additions(paths); end
  def run_on_modifications(paths); end
  def runner; end
  def runner=(arg0); end
  def start; end
  def stop; end
end
