# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/httmultiparty/all/httmultiparty.rbi
#
# httmultiparty-0.3.16
module HTTMultiParty
  def self.delete(*args); end
  def self.does_not_need_conversion?(value); end
  def self.file?(value); end
  def self.file_present?(params); end
  def self.file_present_in_array?(ary); end
  def self.file_to_upload_io(file, detect_mime_type = nil); end
  def self.flatten_params(params = nil, prefix = nil); end
  def self.get(*args); end
  def self.head(*args); end
  def self.included(base); end
  def self.not_a_file?(value); end
  def self.options(*args); end
  def self.post(*args); end
  def self.prepare_value!(value, detect_mime_type); end
  def self.put(*args); end
  def self.query_string_normalizer(options = nil); end
  def self.upload_io?(value); end
end
module HTTMultiParty::Multipartable
  def body=(value); end
  def boundary; end
  def initialize_http_header(initheader); end
  def set_headers_for_body; end
end
class HTTMultiParty::MultipartPost < Net::HTTP::Post
  include HTTMultiParty::Multipartable
end
class HTTMultiParty::MultipartPut < Net::HTTP::Put
  include HTTMultiParty::Multipartable
end
module HTTMultiParty::ClassMethods
  def hash_contains_files?(hash); end
  def post(path, options = nil); end
  def put(path, options = nil); end
end
class HTTMultiParty::Basement
  def self.default_cookies; end
  def self.default_cookies=(arg0); end
  def self.default_options; end
  def self.default_options=(arg0); end
  extend HTTMultiParty::ClassMethods
  extend HTTParty::ClassMethods
  extend HTTParty::ModuleInheritableAttributes::ClassMethods
  include HTTMultiParty
  include HTTParty
  include HTTParty::ModuleInheritableAttributes
end
