# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/opencpu/all/opencpu.rbi
#
# opencpu-0.12.0
module OpenCPU
  def self.client; end
  def self.configuration; end
  def self.configuration=(arg0); end
  def self.configure; end
  def self.disable_test_mode!; end
  def self.enable_test_mode!; end
  def self.reset_configuration!; end
  def self.set_fake_response!(package, script, response = nil); end
  def self.test_mode?; end
end
class OpenCPU::Configuration
  def add_fake_response(key, response); end
  def endpoint_url; end
  def endpoint_url=(arg0); end
  def fake_responses; end
  def fake_responses=(arg0); end
  def initialize; end
  def mode; end
  def mode=(arg0); end
  def password; end
  def password=(arg0); end
  def remove_fake_response(key); end
  def reset!; end
  def timeout; end
  def timeout=(arg0); end
  def username; end
  def username=(arg0); end
  def verify_ssl; end
  def verify_ssl=(arg0); end
end
module OpenCPU::Errors
end
class OpenCPU::Errors::OpenCPUError < StandardError
end
class OpenCPU::Errors::BadRequest < OpenCPU::Errors::OpenCPUError
end
class OpenCPU::Errors::InternalServerError < OpenCPU::Errors::OpenCPUError
end
class OpenCPU::Errors::AccessDenied < OpenCPU::Errors::OpenCPUError
end
class OpenCPU::Client
  def convert_na_to_nil(data); end
  def derive_key_from_url(url); end
  def description(package, options = nil); end
  def error_class_for(response_code); end
  def execute(package, function, options = nil); end
  def fake_response_for(url); end
  def function_url(package, function, user = nil, github_remote = nil, format = nil); end
  def initialize; end
  def package_url(package, user = nil, github_remote = nil); end
  def prepare(package, function, options = nil); end
  def process_query(url, data, format, &block); end
  def request_options(data, format); end
  def self.default_cookies; end
  def self.default_cookies=(arg0); end
  def self.default_options; end
  def self.default_options=(arg0); end
  extend HTTMultiParty::ClassMethods
  extend HTTParty::ClassMethods
  extend HTTParty::ModuleInheritableAttributes::ClassMethods
  include HTTMultiParty
  include HTTParty
  include HTTParty::ModuleInheritableAttributes
  include OpenCPU::Errors
end
class OpenCPU::UnsupportedFormatError < StandardError
end
class OpenCPU::ResponseNotAvailableError < StandardError
end
class OpenCPU::DelayedCalculation
  def available_resources; end
  def available_resources=(arg0); end
  def console; end
  def domain; end
  def graphics(which = nil, type = nil); end
  def info; end
  def initialize(location, resources = nil); end
  def key(uri, location); end
  def location; end
  def location=(arg0); end
  def parse_resources(location, resources); end
  def process_resource(resource); end
  def self.default_cookies; end
  def self.default_cookies=(arg0); end
  def self.default_options; end
  def self.default_options=(arg0); end
  def source; end
  def stdout; end
  def value; end
  def warnings; end
  extend HTTMultiParty::ClassMethods
  extend HTTParty::ClassMethods
  extend HTTParty::ModuleInheritableAttributes::ClassMethods
  include HTTMultiParty
  include HTTParty
  include HTTParty::ModuleInheritableAttributes
end
