# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/poltergeist/all/poltergeist.rbi
#
# poltergeist-1.18.1
module Capybara
end
module Capybara::Poltergeist
  def self.mri?; end
  def self.windows?; end
end
class Capybara::Poltergeist::Driver < Capybara::Driver::Base
  def accept_modal(type, options = nil); end
  def add_header(name, value, options = nil); end
  def add_headers(headers); end
  def app; end
  def basic_authorize(user, password); end
  def body; end
  def browser; end
  def clear_cookies; end
  def clear_memory_cache; end
  def clear_network_traffic; end
  def click(x, y); end
  def client; end
  def client_pid; end
  def close_window(handle); end
  def cookies; end
  def cookies_enabled=(flag); end
  def current_url; end
  def current_window_handle; end
  def debug; end
  def default_cookie_host; end
  def dismiss_modal(type, options = nil); end
  def evaluate_async_script(script, *args); end
  def evaluate_script(script, *args); end
  def execute_script(script, *args); end
  def find(method, selector); end
  def find_css(selector); end
  def find_modal(options); end
  def find_xpath(selector); end
  def frame_title; end
  def frame_url; end
  def go_back; end
  def go_forward; end
  def headers; end
  def headers=(headers); end
  def html; end
  def initialize(app, options = nil); end
  def inspector; end
  def invalid_element_errors; end
  def logger; end
  def maximize_window(handle); end
  def needs_server?; end
  def network_traffic(type = nil); end
  def no_such_window_error; end
  def open_new_window; end
  def options; end
  def paper_size=(size = nil); end
  def pause; end
  def phantomjs_logger; end
  def phantomjs_options; end
  def quit; end
  def refresh; end
  def remove_cookie(name); end
  def render(path, options = nil); end
  def render_base64(format = nil, options = nil); end
  def reset!; end
  def resize(width, height); end
  def resize_window(width, height); end
  def resize_window_to(handle, width, height); end
  def response_headers; end
  def restart; end
  def save_screenshot(path, options = nil); end
  def screen_size; end
  def scroll_to(left, top); end
  def server; end
  def session_wait_time; end
  def set_cookie(name, value, options = nil); end
  def set_proxy(ip, port, type = nil, user = nil, password = nil); end
  def source; end
  def status_code; end
  def switch_to_frame(locator); end
  def switch_to_window(handle); end
  def timeout; end
  def timeout=(sec); end
  def title; end
  def unwrap_script_result(arg); end
  def visit(url); end
  def wait?; end
  def window_handles; end
  def window_size(handle); end
  def within_frame(name, &block); end
  def within_window(name, &block); end
  def zoom_factor=(zoom_factor); end
end
class Capybara::Poltergeist::Error < StandardError
end
class Capybara::Poltergeist::NoSuchWindowError < Capybara::Poltergeist::Error
end
class Capybara::Poltergeist::ClientError < Capybara::Poltergeist::Error
  def initialize(response); end
  def response; end
end
class Capybara::Poltergeist::JSErrorItem
  def initialize(message, stack); end
  def message; end
  def stack; end
  def to_s; end
end
class Capybara::Poltergeist::BrowserError < Capybara::Poltergeist::ClientError
  def error_parameters; end
  def message; end
  def name; end
end
class Capybara::Poltergeist::JavascriptError < Capybara::Poltergeist::ClientError
  def javascript_errors; end
  def message; end
end
class Capybara::Poltergeist::StatusFailError < Capybara::Poltergeist::ClientError
  def details; end
  def message; end
  def url; end
end
class Capybara::Poltergeist::FrameNotFound < Capybara::Poltergeist::ClientError
  def message; end
  def name; end
end
class Capybara::Poltergeist::InvalidSelector < Capybara::Poltergeist::ClientError
  def message; end
  def method; end
  def selector; end
end
class Capybara::Poltergeist::NodeError < Capybara::Poltergeist::ClientError
  def initialize(node, response); end
  def node; end
end
class Capybara::Poltergeist::ObsoleteNode < Capybara::Poltergeist::NodeError
  def message; end
end
class Capybara::Poltergeist::UnsupportedFeature < Capybara::Poltergeist::ClientError
  def message; end
  def name; end
  def unsupported_message; end
  def version; end
end
class Capybara::Poltergeist::MouseEventFailed < Capybara::Poltergeist::NodeError
  def message; end
  def name; end
  def position; end
  def selector; end
end
class Capybara::Poltergeist::KeyError < ArgumentError
  def initialize(response); end
end
class Capybara::Poltergeist::TimeoutError < Capybara::Poltergeist::Error
  def initialize(message); end
  def message; end
end
class Capybara::Poltergeist::ScriptTimeoutError < Capybara::Poltergeist::Error
  def message; end
end
class Capybara::Poltergeist::DeadClient < Capybara::Poltergeist::Error
  def initialize(message); end
  def message; end
end
class Capybara::Poltergeist::PhantomJSTooOld < Capybara::Poltergeist::Error
  def self.===(other); end
end
class Capybara::Poltergeist::PhantomJSFailed < Capybara::Poltergeist::Error
  def self.===(other); end
end
class Capybara::Poltergeist::Command
  def args; end
  def args=(arg0); end
  def id; end
  def initialize(name, *args); end
  def message; end
  def name; end
end
class Capybara::Poltergeist::Browser
  def accept_confirm; end
  def accept_prompt(response); end
  def add_header(header, options = nil); end
  def add_headers(headers); end
  def all_text(page_id, id); end
  def attribute(page_id, id, name); end
  def attributes(page_id, id); end
  def body; end
  def check_render_options!(options); end
  def clear_cookies; end
  def clear_memory_cache; end
  def clear_network_traffic; end
  def click(page_id, id, keys = nil, offset = nil); end
  def click_coordinates(x, y); end
  def client; end
  def close_window(handle); end
  def command(name, *args); end
  def cookies; end
  def cookies_enabled=(flag); end
  def current_url; end
  def debug=(val); end
  def delete_text(page_id, id); end
  def disabled?(page_id, id); end
  def dismiss_confirm; end
  def dismiss_prompt; end
  def double_click(page_id, id, keys = nil, offset = nil); end
  def drag(page_id, id, other_id); end
  def drag_by(page_id, id, x, y); end
  def equals(page_id, id, other_id); end
  def evaluate(script, *args); end
  def evaluate_async(script, wait_time, *args); end
  def execute(script, *args); end
  def extensions=(names); end
  def find(method, selector); end
  def find_window_handle(locator); end
  def find_within(page_id, id, method, selector); end
  def frame_title; end
  def frame_url; end
  def get_headers; end
  def go_back; end
  def go_forward; end
  def hover(page_id, id); end
  def initialize(server, client, logger = nil); end
  def js_errors=(val); end
  def log(message); end
  def logger; end
  def modal_message; end
  def network_traffic(type = nil); end
  def normalize_keys(keys); end
  def open_new_window; end
  def page_settings=(settings); end
  def parents(page_id, id); end
  def path(page_id, id); end
  def property(page_id, id, name); end
  def refresh; end
  def remove_cookie(name); end
  def render(path, options = nil); end
  def render_base64(format, options = nil); end
  def reset; end
  def resize(width, height); end
  def response_headers; end
  def restart; end
  def right_click(page_id, id, keys = nil, offset = nil); end
  def scroll_to(left, top); end
  def select(page_id, id, value); end
  def select_file(page_id, id, value); end
  def send_keys(page_id, id, keys); end
  def server; end
  def set(page_id, id, value); end
  def set_cookie(cookie); end
  def set_headers(headers); end
  def set_http_auth(user, password); end
  def set_paper_size(size); end
  def set_proxy(ip, port, type, user, password); end
  def set_zoom_factor(zoom_factor); end
  def source; end
  def status_code; end
  def switch_to_frame(handle); end
  def switch_to_window(handle); end
  def tag_name(page_id, id); end
  def title; end
  def trigger(page_id, id, event); end
  def url_blacklist=(blacklist); end
  def url_whitelist=(whitelist); end
  def value(page_id, id); end
  def visible?(page_id, id); end
  def visible_text(page_id, id); end
  def visit(url); end
  def window_handle; end
  def window_handles; end
  def within_frame(handle, &block); end
  def within_window(locator, &block); end
end
class Capybara::Poltergeist::Node < Capybara::Driver::Node
  def ==(other); end
  def [](name); end
  def all_text; end
  def as_json(*arg0); end
  def attributes; end
  def browser; end
  def checked?; end
  def click(keys = nil, offset = nil); end
  def command(name, *args); end
  def disabled?; end
  def double_click(keys = nil, offset = nil); end
  def drag_by(x, y); end
  def drag_to(other); end
  def filter_text(text, visible = nil); end
  def find(method, selector); end
  def find_css(selector); end
  def find_xpath(selector); end
  def hover; end
  def id; end
  def initialize(driver, page_id, id); end
  def page_id; end
  def parents; end
  def path; end
  def property(name); end
  def right_click(keys = nil, offset = nil); end
  def select_option; end
  def selected?; end
  def send_key(*keys); end
  def send_keys(*keys); end
  def set(value, options = nil); end
  def tag_name; end
  def to_json(*arg0); end
  def trigger(event); end
  def unselect_option; end
  def value; end
  def visible?; end
  def visible_text; end
end
class Capybara::Poltergeist::Server
  def custom_host; end
  def fixed_port; end
  def host; end
  def initialize(fixed_port = nil, timeout = nil, custom_host = nil); end
  def port; end
  def restart; end
  def send(command); end
  def socket; end
  def start; end
  def stop; end
  def timeout; end
  def timeout=(sec); end
end
class Capybara::Poltergeist::WebSocketServer
  def accept; end
  def close; end
  def connected?; end
  def driver; end
  def host; end
  def initialize(port = nil, timeout = nil, custom_host = nil); end
  def port; end
  def receive(cmd_id, receive_timeout = nil); end
  def send(cmd_id, message, accept_timeout = nil); end
  def server; end
  def socket; end
  def start_server(port, custom_host); end
  def timeout; end
  def timeout=(arg0); end
  def write(data); end
end
class Capybara::Poltergeist::Client
  def close_io; end
  def command; end
  def initialize(server, options = nil); end
  def kill_phantomjs; end
  def path; end
  def phantomjs_options; end
  def pid; end
  def redirect_stdout; end
  def restart; end
  def self.process_killer(pid); end
  def self.start(*args); end
  def server; end
  def start; end
  def stop; end
  def window_size; end
end
class Capybara::Poltergeist::Inspector
  def browser; end
  def initialize(browser = nil, port = nil); end
  def open(scheme); end
  def port; end
  def self.browser_binary_exists?(browser); end
  def self.detect_browser; end
  def url(scheme); end
end
module Capybara::Poltergeist::NetworkTraffic
end
class Capybara::Poltergeist::NetworkTraffic::Request
  def error; end
  def headers; end
  def initialize(data, response_parts = nil, error = nil); end
  def method; end
  def response_parts; end
  def time; end
  def url; end
end
class Capybara::Poltergeist::NetworkTraffic::Response
  def body_size; end
  def content_type; end
  def headers; end
  def initialize(data); end
  def redirect_url; end
  def status; end
  def status_text; end
  def time; end
  def url; end
end
class Capybara::Poltergeist::NetworkTraffic::Error
  def code; end
  def description; end
  def initialize(data); end
  def url; end
end
class Capybara::Poltergeist::Cookie
  def domain; end
  def expires; end
  def httponly?; end
  def initialize(attributes); end
  def name; end
  def path; end
  def samesite; end
  def secure?; end
  def value; end
end
