# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ref/all/ref.rbi
#
# ref-2.0.0
module Ref
  def self.jruby?; end
end
class Ref::AbstractReferenceValueMap
  def [](key); end
  def []=(key, value); end
  def clear; end
  def delete(key); end
  def each; end
  def empty?; end
  def get(key); end
  def initialize; end
  def inspect; end
  def length; end
  def merge!(other_hash); end
  def merge(other_hash, &block); end
  def put(key, value); end
  def remove_reference_to(object_id); end
  def self.reference_class; end
  def self.reference_class=(klass); end
  def size; end
  def to_a; end
  def to_h; end
  def values; end
end
class Ref::AbstractReferenceKeyMap
  def [](key); end
  def []=(key, value); end
  def clear; end
  def delete(key); end
  def each; end
  def empty?; end
  def get(key); end
  def initialize; end
  def inspect; end
  def keys; end
  def length; end
  def merge!(other_hash); end
  def merge(other_hash, &block); end
  def put(key, value); end
  def ref_key(key); end
  def remove_reference_to(object_id); end
  def self.reference_class; end
  def self.reference_class=(klass); end
  def size; end
  def to_a; end
  def to_h; end
end
class Ref::Reference
  def initialize(obj); end
  def inspect; end
  def object; end
  def referenced_object_id; end
end
class Ref::ReferenceQueue
  def empty?; end
  def initialize; end
  def monitor(reference); end
  def pop; end
  def push(reference); end
  def shift; end
  def size; end
end
class Ref::SoftReference < Ref::Reference
  def add_strong_reference(obj); end
  def initialize(obj); end
  def object; end
end
class Ref::WeakReference < Ref::Reference
  def initialize(obj); end
  def object; end
end
class Ref::SoftKeyMap < Ref::AbstractReferenceKeyMap
end
class Ref::SoftValueMap < Ref::AbstractReferenceValueMap
end
class Ref::StrongReference < Ref::Reference
  def initialize(obj); end
  def object; end
end
class Ref::WeakKeyMap < Ref::AbstractReferenceKeyMap
end
class Ref::WeakValueMap < Ref::AbstractReferenceValueMap
end
