# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/roqua-support/all/roqua-support.rbi
#
# roqua-support-0.1.34
module Roqua
  def self.appname; end
  def self.appname=(name); end
  def self.logger; end
  def self.logger=(logger); end
  def self.stats; end
  def self.stats=(stats); end
end
module Roqua::Support
end
class Roqua::Railtie < Rails::Railtie
end
class RoquaLoggingRailtie < Rails::Railtie
  def self.configure; end
  def self.output_stream; end
end
class Roqua::LogWrapper
  def add(level, message, options = nil); end
  def debug(*args); end
  def error(*args); end
  def fatal(*args); end
  def info(*args); end
  def initialize(logger); end
  def lifecycle(message, options = nil); end
  def logger; end
  def warn(*args); end
end
module Roqua::Support::Instrumentation
  def eventlog; end
  def with_instrumentation(message, options = nil); end
end
module Roqua::Support::Errors
  def self.add_parameters(params); end
  def self.appsignal_namespace_for_category(category); end
  def self.extra_parameters; end
  def self.extra_parameters=(hash); end
  def self.extra_parameters_from_exception(exception); end
  def self.log_exception(exception, parameters = nil, notification_urls = nil, skip_backtrace = nil); end
  def self.merge_parameters(exception, context = nil); end
  def self.notify_appsignal(exception, labels, namespace); end
  def self.notify_appsignal?(exception); end
  def self.report(exception, context = nil); end
end
class Roqua::Support::Stats
  def backend; end
  def initialize(backend = nil); end
  def prefix(key); end
  def submit(key, value); end
end
module Roqua::Support::Stats::NullBackend::Customizations
end
module Roqua::Support::Stats::NullBackend::GeneratedMethods
  def initialize(*arg0); end
  def inspect; end
  def method_missing(*arg0); end
  def respond_to?(*arg0); end
end
class Roqua::Support::Stats::NullBackend < Naught::BasicObject
  def class; end
  def clone; end
  def dup; end
  def self.allocate; end
  def self.get(*arg0); end
  def self.instance; end
  def self.new(*arg0); end
  extend Singleton::SingletonClassMethods
  include Naught::Conversions
  include Naught::NullObjectTag
  include Roqua::Support::Stats::NullBackend::Customizations
  include Roqua::Support::Stats::NullBackend::GeneratedMethods
  include Singleton
end
module Roqua::Probes
end
module Roqua::Responders
end
module Roqua::Scheduling
end
module Roqua::StatusChecks
end
module Roqua::Support::RequestLogging
  def add_log_information(key, value); end
end
class Roqua::Support::RequestLogger < ActiveSupport::LogSubscriber
  include Roqua::Support::Instrumentation
end
