# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/teaspoon-jasmine/all/teaspoon-jasmine.rbi
#
# teaspoon-jasmine-2.3.4
module Teaspoon
end
module Teaspoon::Jasmine
end
class Teaspoon::Jasmine::Framework < Teaspoon::Framework::Base
end
