# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/test-unit/all/test-unit.rbi
#
# test-unit-3.2.8
module Test
end
module Test::Unit
end
class Object < BasicObject
  def run_test; end
end
