# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/therubyracer/all/therubyracer.rbi
#
# therubyracer-0.12.3
module V8
  def self.Error(trycatch); end
end
module V8::Weak
end
class V8::Weak::Ref
  def initialize(object); end
  def object; end
end
class V8::Weak::WeakValueMap
  def [](key); end
  def []=(key, value); end
  def initialize; end
  def self.ensure_cleanup(values, key, ref); end
end
module V8::Weak::Cell
  def weakcell(name, &block); end
end
class V8::Weak::Cell::Storage
  def access(&block); end
  def populate(block); end
end
class V8::C::V8
  def self.AdjustAmountOfExternalAllocatedMemory(arg0); end
  def self.ContextDisposedNotification; end
  def self.Dispose; end
  def self.GetCurrentThreadId; end
  def self.GetHeapStatistics(arg0); end
  def self.GetVersion; end
  def self.IdleNotification(*arg0); end
  def self.IsExecutionTerminating; end
  def self.IsProfilerPaused; end
  def self.LowMemoryNotification; end
  def self.PauseProfiler; end
  def self.ResumeProfiler; end
  def self.SetCaptureStackTraceForUncaughtExceptions(*arg0); end
  def self.SetFlagsFromCommandLine(arg0, arg1); end
  def self.SetFlagsFromString(arg0); end
  def self.TerminateExecution(arg0); end
  def self.new(*arg0); end
end
module V8::C
  def self.False; end
  def self.HandleScope(*arg0); end
  def self.Locker(*arg0); end
  def self.Null; end
  def self.SetResourceConstraints(arg0); end
  def self.ThrowException(arg0); end
  def self.True; end
  def self.TryCatch(*arg0); end
  def self.Undefined; end
  def self.Unlocker(*arg0); end
end
class V8::C::AccessorInfo
  def Data; end
  def Holder; end
  def This; end
  def self.new(*arg0); end
end
class V8::C::Context
  def AllowCodeGenerationFromStrings(arg0); end
  def DetachGlobal; end
  def Dispose; end
  def Enter; end
  def Exit; end
  def GetEmbedderData(arg0); end
  def GetSecurityToken; end
  def Global; end
  def HasOutOfMemoryException; end
  def IsCodeGenerationFromStringsAllowed; end
  def ReattachGlobal(arg0); end
  def SetEmbedderData(arg0, arg1); end
  def SetSecurityToken(arg0); end
  def UseDefaultSecurityToken; end
  def self.GetCalling; end
  def self.GetCurrent; end
  def self.GetEntered; end
  def self.InContext; end
  def self.New(*arg0); end
  def self.new(*arg0); end
end
class V8::C::ExtensionConfiguration
  def self.new(arg0); end
end
class V8::C::Arguments
  def Callee; end
  def Data; end
  def Holder; end
  def IsConstructCall; end
  def Length; end
  def This; end
  def [](arg0); end
  def self.new(*arg0); end
end
class V8::C::Signature
  def New(*arg0); end
  def self.new(*arg0); end
end
class V8::C::Value
  def BooleanValue; end
  def Equals(arg0); end
  def IntegerValue; end
  def IsArray; end
  def IsBoolean; end
  def IsBooleanObject; end
  def IsDate; end
  def IsExternal; end
  def IsFalse; end
  def IsFunction; end
  def IsInt32; end
  def IsNativeError; end
  def IsNull; end
  def IsNumber; end
  def IsNumberObject; end
  def IsObject; end
  def IsRegExp; end
  def IsString; end
  def IsStringObject; end
  def IsTrue; end
  def IsUint32; end
  def IsUndefined; end
  def NumberValue; end
  def StrictEquals(arg0); end
  def ToDetailString; end
  def ToObject; end
  def ToString; end
  def Uint32Value; end
  def self.new(*arg0); end
end
class V8::C::String < V8::C::Primitive
  def Utf8Value; end
  def self.Concat(arg0, arg1); end
  def self.New(arg0); end
  def self.NewSymbol(arg0); end
  include V8::Conversion::NativeString
end
class V8::C::Object < V8::C::Value
  def CallAsConstructor(arg0); end
  def CallAsFunction(arg0, arg1); end
  def Clone; end
  def CreationContext; end
  def Delete(arg0); end
  def DeleteHiddenValue(arg0); end
  def FindInstanceInPrototypeChain(arg0); end
  def ForceDelete(arg0); end
  def ForceSet(arg0, arg1); end
  def Get(arg0); end
  def GetConstructorName; end
  def GetHiddenValue(arg0); end
  def GetIdentityHash; end
  def GetIndexedPropertiesExternalArrayData; end
  def GetIndexedPropertiesExternalArrayDataLength; end
  def GetIndexedPropertiesExternalArrayDataType; end
  def GetIndexedPropertiesPixelData; end
  def GetIndexedPropertiesPixelDataLength; end
  def GetInternalField(arg0); end
  def GetOwnPropertyNames; end
  def GetPropertyAttributes(arg0); end
  def GetPropertyNames; end
  def GetPrototype; end
  def GetRealNamedProperty(arg0); end
  def GetRealNamedPropertyInPrototypeChain(arg0); end
  def Has(arg0); end
  def HasIndexedLookupInterceptor; end
  def HasIndexedPropertiesInExternalArrayData; end
  def HasIndexedPropertiesToPixelData; end
  def HasNamedLookupInterceptor; end
  def HasOwnProperty(arg0); end
  def HasRealIndexedProperty(arg0); end
  def HasRealNamedCallbackProperty(arg0); end
  def HasRealNamedProperty(arg0); end
  def InternalFieldCount; end
  def IsCallable; end
  def IsDirty; end
  def ObjectProtoToString; end
  def Set(arg0, arg1); end
  def SetAccessor(*arg0); end
  def SetHiddenValue(arg0, arg1); end
  def SetIndexedPropertiesToExternalArrayData; end
  def SetIndexedPropertiesToPixelData(arg0, arg1); end
  def SetInternalField(arg0, arg1); end
  def SetPrototype(arg0); end
  def TurnOnAccessCheck; end
  def self.New; end
  include V8::Conversion::NativeObject
end
class V8::C::PropertyAttribute
  def self.new(*arg0); end
end
class V8::C::AccessControl
  def self.new(*arg0); end
end
class V8::C::Array < V8::C::Object
  def CloneElementAt(arg0); end
  def Length; end
  def self.New(*arg0); end
end
class V8::C::Function < V8::C::Object
  def Call(arg0, arg1); end
  def GetInferredName; end
  def GetName; end
  def GetScriptColumnNumber; end
  def GetScriptId; end
  def GetScriptLineNumber; end
  def GetScriptOrigin; end
  def NewInstance(*arg0); end
  def SetName(arg0); end
end
class V8::C::Date < V8::C::Value
  def NumberValue; end
  def self.New(arg0); end
  include V8::Conversion::NativeDate
end
class V8::C::External < V8::C::Value
  def Value; end
  def self.New(arg0); end
end
class V8::C::Script
  def Run; end
  def RunWithTimeout(arg0); end
  def self.New(*arg0); end
  def self.new(*arg0); end
end
class V8::C::ScriptOrigin
  def self.new(*arg0); end
end
class V8::C::ScriptData
  def Data; end
  def HasError; end
  def Length; end
  def self.New(arg0, arg1); end
  def self.PreCompile(arg0, arg1); end
  def self.new(*arg0); end
end
class V8::C::Template
  def Set(*arg0); end
  def self.new(*arg0); end
end
class V8::C::ObjectTemplate < V8::C::Template
  def InternalFieldCount; end
  def MarkAsUndetectable; end
  def NewInstance; end
  def SetAccessCheckCallbacks(*arg0); end
  def SetAccessor(*arg0); end
  def SetCallAsFunctionHandler(*arg0); end
  def SetIndexedPropertyHandler(*arg0); end
  def SetInternalFieldCount(arg0); end
  def SetNamedPropertyHandler(*arg0); end
  def self.New; end
end
class V8::C::FunctionTemplate < V8::C::Template
  def GetFunction; end
  def HasInstance(arg0); end
  def Inherit(arg0); end
  def InstanceTemplate; end
  def PrototypeTemplate; end
  def ReadOnlyPrototype; end
  def SetCallHandler(*arg0); end
  def SetClassName(arg0); end
  def SetHiddenPrototype(arg0); end
  def self.New(*arg0); end
end
class V8::C::StackTrace
  def AsArray; end
  def GetFrame(arg0); end
  def GetFrameCount; end
  def self.CurrentStackTrace(*arg0); end
  def self.kColumnOffset; end
  def self.kDetailed; end
  def self.kFunctionName; end
  def self.kIsConstructor; end
  def self.kIsEval; end
  def self.kLineNumber; end
  def self.kOverview; end
  def self.kScriptName; end
  def self.kScriptNameOrSourceURL; end
  def self.new(*arg0); end
end
class V8::C::StackFrame
  def GetColumn; end
  def GetFunctionName; end
  def GetLineNumber; end
  def GetScriptName; end
  def GetScriptNameOrSourceURL; end
  def IsConstructor; end
  def IsEval; end
  def self.new(*arg0); end
end
class V8::C::Message
  def Get; end
  def GetEndPosition; end
  def GetLineNumber; end
  def GetScriptData; end
  def GetScriptResourceName; end
  def GetSourceLine; end
  def GetStackTrace; end
  def GetStartColumn; end
  def GetStartPosition; end
  def self.kNoColumnInfo; end
  def self.kNoLineNumberInfo; end
  def self.new(*arg0); end
end
class V8::C::TryCatch
  def CanContinue; end
  def Exception; end
  def HasCaught; end
  def Message; end
  def ReThrow; end
  def Reset; end
  def SetCaptureMessage(arg0); end
  def SetVerbose(arg0); end
  def StackTrace; end
  def self.new(*arg0); end
end
class V8::C::Exception
  def self.Error(arg0); end
  def self.RangeError(arg0); end
  def self.ReferenceError(arg0); end
  def self.SyntaxError(arg0); end
  def self.TypeError(arg0); end
  def self.new(*arg0); end
end
class V8::C::Locker
  def self.IsActive; end
  def self.IsLocked; end
  def self.StartPreemption(arg0); end
  def self.StopPreemption; end
  def self.new(*arg0); end
end
class V8::C::ResourceConstraints
  def max_executable_size(arg0); end
  def max_old_space_size; end
  def max_young_space_size; end
  def self.new; end
  def set_max_executable_size(arg0); end
  def set_max_old_space_size(arg0); end
  def set_max_young_space_size(arg0); end
end
class V8::C::HeapStatistics
  def heap_size_limit; end
  def self.new; end
  def total_heap_size; end
  def total_heap_size_executable; end
  def total_physical_size; end
  def used_heap_size; end
end
class V8::Error < StandardError
  def backtrace(*modifiers); end
  def bilingual_backtrace(trace_ruby = nil, trace_javascript = nil); end
  def cause; end
  def causes; end
  def in_javascript?; end
  def in_ruby?; end
  def initialize(message, value, javascript_backtrace, cause = nil); end
  def javascript_backtrace; end
  def root_cause; end
  def standard_error_backtrace; end
  def value; end
  include Enumerable
end
module V8::Error::Try
  def try; end
end
module V8::Error::Protect
  def protect; end
end
class V8::StackTrace
  def each; end
  def initialize(native); end
  def length; end
  def to_s; end
  include Enumerable
end
class V8::StackFrame
  def column; end
  def constructor?; end
  def eval?; end
  def function_name; end
  def initialize(native, context); end
  def line_number; end
  def script_name; end
  def to_s; end
end
class V8::Conversion
  def to_ruby(v8_object); end
  def to_v8(ruby_object); end
  include V8::Conversion::Fundamental
  include V8::Conversion::Identity
end
module V8::Conversion::Fundamental
  def to_ruby(v8_object); end
  def to_v8(ruby_object); end
end
module V8::Conversion::Identity
  def equate(ruby_object, v8_object); end
  def rb_idmap; end
  def to_ruby(v8_object); end
  def to_v8(ruby_object); end
  def v8_idmap; end
end
module V8::Conversion::Reference
  def self.construct!(object); end
  def to_v8; end
end
module V8::Conversion::Primitive
  def to_v8; end
end
module V8::Conversion::Code
  def to_template; end
  def to_v8; end
  include V8::Weak::Cell
end
class V8::Conversion::Code::InvocationHandler
  def call(arguments); end
  def initialize(code); end
  include V8::Error::Protect
end
module V8::Conversion::Class
  def to_template; end
  include V8::Conversion::Code
end
class V8::Conversion::Constructor
  def call(arguments); end
  def initialize(cls); end
  include V8::Error::Protect
end
module V8::Conversion::Constructor::Args
  def construct(cls); end
  def context; end
  def link; end
  def linkage_call?; end
  def to_args; end
end
module V8::Conversion::Accessor
  def intercept(info, key, &block); end
  include V8::Error::Protect
end
class V8::Conversion::Get
  def self.call(property, info); end
  extend V8::Conversion::Accessor
end
class V8::Conversion::Set
  def self.call(property, value, info); end
  extend V8::Conversion::Accessor
end
class V8::Conversion::IGet
  def self.call(property, info); end
  extend V8::Conversion::Accessor
end
class V8::Conversion::ISet
  def self.call(property, value, info); end
  extend V8::Conversion::Accessor
end
module V8::Conversion::Object
  def to_ruby; end
  def to_v8; end
end
module V8::Conversion::NativeObject
  def to_ruby; end
  def to_v8; end
end
module V8::Conversion::Time
  def to_v8; end
end
module V8::Conversion::NativeDate
  def to_ruby; end
end
module V8::Conversion::Hash
  def to_v8; end
end
module V8::Conversion::Array
  def to_v8; end
end
module V8::Conversion::Proc
  include V8::Conversion::Code
end
module V8::Conversion::Method
  def to_v8; end
  include V8::Conversion::Code
end
class V8::Conversion::Method::MethodCache
  def [](method); end
  def []=(method, template); end
  def initialize; end
end
module V8::Conversion::Symbol
  def to_v8; end
end
module V8::Conversion::String
  def to_v8; end
end
module V8::Conversion::NativeString
  def to_ruby; end
end
module V8::Conversion::Integer
  def to_ruby; end
  def to_v8; end
end
class TrueClass
  include V8::Conversion::Primitive
end
class FalseClass
  include V8::Conversion::Primitive
end
class NilClass
  include V8::Conversion::Primitive
end
class Float < Numeric
  include V8::Conversion::Primitive
end
class Class < Module
  include V8::Conversion::Class
end
class Object < BasicObject
  include V8::Conversion::Object
end
class Array
  include V8::Conversion::Array
end
class Hash
  include V8::Conversion::Hash
end
class String
  include V8::Conversion::String
end
class Symbol
  include V8::Conversion::Symbol
end
class Time
  include V8::Conversion::Time
end
class Proc
  include V8::Access::Invocation::Proc
  include V8::Conversion::Proc
end
class Method
  include V8::Access::Invocation::Method
  include V8::Conversion::Method
end
class Integer < Numeric
  include V8::Conversion::Integer
end
class UnboundMethod
  include V8::Access::Invocation::UnboundMethod
  include V8::Conversion::Method
end
class V8::Access
  include V8::Access::Indices
  include V8::Access::Invocation
  include V8::Access::Names
end
module V8::Access::Names
  def accessible_names(obj, special_methods = nil); end
  def delete(obj, name, &dontintercept); end
  def get(obj, name, &dontintercept); end
  def names(obj); end
  def query(obj, name, attributes, &dontintercept); end
  def set(obj, name, value, &dontintercept); end
  def special?(name = nil); end
end
module V8::Access::Indices
  def idelete(obj, index, &dontintercept); end
  def iget(obj, index, &dontintercept); end
  def indices(obj); end
  def iquery(obj, index, attributes, &dontintercept); end
  def iset(obj, index, value, &dontintercept); end
end
module V8::Access::Invocation
  def methodcall(code, this, args); end
end
module V8::Access::Invocation::Aritize
  def aritize(args); end
end
module V8::Access::Invocation::Proc
  def methodcall(this, args); end
  include V8::Access::Invocation::Aritize
end
module V8::Access::Invocation::Method
  def methodcall(this, args); end
  include V8::Access::Invocation::Aritize
end
module V8::Access::Invocation::UnboundMethod
  def methodcall(this, args); end
end
class V8::Context
  def [](key); end
  def []=(key, value); end
  def access; end
  def conversion; end
  def dispose; end
  def enter(&block); end
  def entered?; end
  def eval(source, filename = nil, line = nil); end
  def initialize(options = nil); end
  def link(ruby_object, v8_object); end
  def load(filename); end
  def lock_scope_and_enter; end
  def native; end
  def scope; end
  def self.current; end
  def self.current=(context); end
  def self.link(ruby_object, v8_object); end
  def timeout; end
  def to_ruby(v8_object); end
  def to_v8(ruby_object); end
  include V8::Error::Try
end
class V8::Object
  def [](key); end
  def []=(key, value); end
  def each; end
  def initialize(native = nil); end
  def keys; end
  def method_missing(name, *args, &block); end
  def native; end
  def respond_to?(method); end
  def to_s; end
  def to_v8; end
  def values; end
  include Enumerable
end
class V8::Array < V8::Object
  def each; end
  def initialize(native_or_length = nil); end
  def length; end
end
class V8::Function < V8::Object
  def call(*args); end
  def initialize(native = nil); end
  def methodcall(this, *args); end
  def new(*args); end
  include V8::Error::Try
end
