image: "roqua/roqua-build-images:ruby-2.3.3-phantomjs-2.1.1-bundler-gemnasium"

services:
  - "daandavidsz/percona-ci"

variables:
  DATABASE_URL: "mysql2://root:secret@daandavidsz-percona-ci:3306/roqua_test?pool=5"
  MYSQL_ROOT_PASSWORD: "secret"
  SIMPLECOV: "true"
  RAILS_ENV: 'test'
  TEASPOON_RAILS_ENV: 'settings_this_prevents_teaspoon_from_loading_rails_too_soon'

before_script:
  - ruby -v
  - eval $(ssh-agent -s)

  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

  - bundle-cache
  - bundle install --gemfile="$BUNDLE_GEMFILE"
  - bundle exec rspec spec
  - bundle exec teaspoon  

rails_41:
  variables:
    BUNDLE_GEMFILE: 'gemfiles/rails41.gemfile'
  script:
    - echo 'Done!'

rails_42:
  variables:
    BUNDLE_GEMFILE: 'gemfiles/rails42.gemfile'
  script:
    - echo 'Done!'

rails_5:
  variables:
    BUNDLE_GEMFILE: 'gemfiles/rails5.gemfile'
  script:
    - echo 'Done!'    
