variables:
  SIMPLECOV: 'true'
  RAILS_ENV: 'test'
  TEASPOON_RAILS_ENV: 'setting_this_prevents_teaspoon_from_loading_rails_too_soon'

.ruby_before_script: &ruby_before_script
  before_script:
    - export BUNDLE_PATH=$CI_PROJECT_DIR/.gems
    - bundle --jobs 2 --retry 3
    - bundle exec appraisal install

.ruby_24: &ruby_24
  <<: *ruby_before_script
  image: registry.roqua.nl/roqua/docker-base-images:ruby-2.4
  cache:
    key: ruby_24
    paths:
      - .gems

rails_50_ruby_24:
  <<: *ruby_24
  script:
    - cat gemfiles/rails50.gemfile.lock
    - bundle exec appraisal rails50 rspec
    - bundle exec appraisal rails50 teaspoon

rails_51_ruby_24:
  <<: *ruby_24
  script:
    - cat gemfiles/rails51.gemfile.lock
    - bundle exec appraisal rails51 rspec
    - bundle exec appraisal rails51 teaspoon

rails_52_ruby_24:
  <<: *ruby_24
  script:
    - cat gemfiles/rails52.gemfile.lock
    - bundle exec appraisal rails52 rspec
    - bundle exec appraisal rails52 teaspoon

dependency_scanning:
  image: registry.roqua.nl/roqua/dependency_scanning
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:stable-dind
  script:
    - scan_dependencies.sh
  artifacts:
    paths: [gl-dependency-scanning-report.json]

code_quality:
  image: docker:stable
  stage: test
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  before_script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
  script:
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]
