variables:
  SIMPLECOV: 'true'
  RAILS_ENV: 'test'
  TEASPOON_RAILS_ENV: 'settings_this_prevents_teaspoon_from_loading_rails_too_soon'

before_script:
  - ruby -v
  - eval $(ssh-agent -s)

  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

  - bundle-cache
  - bundle exec appraisal install
  - bundle exec appraisal rails50 bundle exec rspec spec
  - bundle exec appraisal rails50 bundle exec teaspoon  

rails_50_ruby_23:
  image: "roqua/roqua-build-images:ruby-2.3-rails-base-test"
  script:
    - echo 'Done!'

rails_50_ruby_24:
  image: "roqua/roqua-build-images:ruby-2.4-rails-base-test"
  script:
    - echo 'Done!'
