inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/*.rb'
    - 'spec/dummy/**/*'

Rails:
  Enabled: true

# Use UTF-8 as the source file encoding.
Encoding:
  Enabled: false

# Limit lines to 80 characters.
LineLength:
  Max: 120
  Exclude:
    - 'quby.gemspec'

# Avoid methods longer than 10 lines of code
MethodLength:
  CountComments: false  # count full line comments?
  Max: 25 # need to go lower.
  Exclude:
    - 'spec/features'

BracesAroundHashParameters:
  Enabled: false

SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'spec/**/*'

CyclomaticComplexity:
  Max: 15 # should be set to 6, too many for now

ParameterLists:
  Max: 6

################################################################## DISABLED COPS
# These cops are disabled because we think they are a Bad Idea. If you add one
# here, make sure to add a comment describing what the cop does, and why this
# is a bad idea.

# Forces the argument names of the block given to #reduce to be `a, e`. Only
# applies on single-line blocks, but why would we want to force people to use
# less descriptive names?
SingleLineBlockParams:
  Enabled: false

# Complains than multiline ternary expressions should be if/else statements
# Ternary are still often more readable.
MultilineTernaryOperator:
  Enabled: false

# disallows `class Quby::Questionnaires::Entities::Text` style definitions.
# Why waste all that indentation?
ClassAndModuleChildren:
  Enabled: false

# This is not universally a better idea, it depends greatly on whether the
# condition is to handle an edge-case or not. We prefer leaving this up to
# code review instead of Rubocop.
IfUnlessModifier:
  Enabled: false

# before_filter must be renamed to before_action.
# can't enable this until we drop support for rails 3.
ActionFilter:
  Enabled: false

# Use single quotes for strings that don't do string interpolation. Makes it
# harder to later add an interpolated value.
StringLiterals:
  Enabled: false

# This forces the use of the English library instead of $: etc. We think that some
# of these Perl-vars are quite succinct.
SpecialGlobalVars:
  Enabled: false

# This forces the use of %r{.. } when a regexp contains more than one slash.
# If a regex is unreadable, code review will catch it, otherwise it's not
# a function of how many slashes are in it.
RegexpLiteral:
  Enabled: false

# Requires you a space inside the braces of a Hash literal. I have never ever done this before and
# do not think it makes for more readable code.
SpaceInsideHashLiteralBraces:
  Enabled: false

# can only use %w(..)
# Stupid rule, the whole idea of the %w is to be able to use something that will not be in the string.
PercentLiteralDelimiters:
  Enabled: false
