#!/bin/bash -l -e
rvm use ruby-1.9.3-p0@quby
bundle install > /dev/null

if [ -f spec/dummy/config/mongoid.yml.tpl ]; then
  cp spec/dummy/config/mongoid.yml.tpl spec/dummy/config/mongoid.yml
fi

MONGOID_DATABASE=$JOB_NAME bundle exec rspec spec -b --format=documentation --color